#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ANS_ChangePitch

#include "Basic.hpp"

#include "Extensions_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ANS_ChangePitch.ANS_ChangePitch_C
// 0x0000 (0x00C8 - 0x00C8)
class UANS_ChangePitch_C final : public UANS_ChangePitch
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ANS_ChangePitch_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ANS_ChangePitch_C")
	}
	static class UANS_ChangePitch_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UANS_ChangePitch_C>();
	}
};
DUMPER7_ASSERTS_UANS_ChangePitch_C;

}

