#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BindableCineActor

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_BindableCineActor.BP_BindableCineActor_C.Get_PC_ABP_Cinematics_HumanBone
// 0x0008 (0x0008 - 0x0000)
struct BP_BindableCineActor_C_Get_PC_ABP_Cinematics_HumanBone final
{
public:
	class UAnimInstance*                          ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_BindableCineActor_C_Get_PC_ABP_Cinematics_HumanBone;

// Function BP_BindableCineActor.BP_BindableCineActor_C.IsPlayer
// 0x0001 (0x0001 - 0x0000)
struct BP_BindableCineActor_C_IsPlayer final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_BindableCineActor_C_IsPlayer;

}

