#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ConfigurationUIObject

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BasicUI_structs.hpp"
#include "GameplayTags_structs.hpp"
#include "Extensions_structs.hpp"
#include "Extensions_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ConfigurationUIObject.BP_ConfigurationUIObject_C
// 0x0398 (0x0460 - 0x00C8)
class UBP_ConfigurationUIObject_C final : public UConfigurationUIObject
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x00C8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FMenuContext                           GamePageContext;                                   // 0x00D0(0x0038)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	struct FMenuContext                           AudioPageContext;                                  // 0x0108(0x0038)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	struct FMenuContext                           LanguagePageContext;                               // 0x0140(0x0038)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	struct FMenuContext                           CameraPageContext;                                 // 0x0178(0x0038)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	struct FMenuContext                           GraphicPageContext;                                // 0x01B0(0x0038)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	struct FMenuContext                           GraphicConsolePageContext;                         // 0x01E8(0x0038)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	struct FMenuContext                           BrightnessPageContext;                             // 0x0220(0x0038)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	struct FMenuContext                           NetworkPageContext;                                // 0x0258(0x0038)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	struct FMenuContext                           AccessibilityPageContext;                          // 0x0290(0x0038)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	struct FMenuContext                           KeyAssignPageContext;                              // 0x02C8(0x0038)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	struct FMenuContext                           ConsentSelectPageContext;                          // 0x0300(0x0038)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	struct FMenuContext                           ConsentSelectPPAnalyticsPageContext;               // 0x0338(0x0038)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	struct FMenuContext                           ConsentPageContext;                                // 0x0370(0x0038)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	struct FMenuContext                           OperationTopPageContext;                           // 0x03A8(0x0038)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	class UMenuBase*                              CurrentOpenMenu;                                   // 0x03E0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UMenuBase*                              GamePage;                                          // 0x03E8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UMenuBase*                              AudioPage;                                         // 0x03F0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UMenuBase*                              LanguagePage;                                      // 0x03F8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UMenuBase*                              CameraPage;                                        // 0x0400(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UMenuBase*                              GraphicPage;                                       // 0x0408(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UMenuBase*                              BrightnessPage;                                    // 0x0410(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UMenuBase*                              NetworkPage;                                       // 0x0418(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UMenuBase*                              AccessibilityPage;                                 // 0x0420(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UMenuBase*                              KeyAssignPage;                                     // 0x0428(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UMenuBase*                              ConsentSelectPage;                                 // 0x0430(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UMenuBase*                              ConsentPage;                                       // 0x0438(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UMenuBase*                              OperationTopPage;                                  // 0x0440(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTag                           TransitTypeTag;                                    // 0x0448(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	TMulticastInlineDelegate<void()>              OnChangeTransitTypeEvent;                          // 0x0450(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)

public:
	void CloseFieldMenu();
	void ExecuteUbergraph_BP_ConfigurationUIObject(int32 EntryPoint);
	void GetTransitType(struct FGameplayTag* TransitTypeTag_0);
	void OnAccessibilityPageClose();
	void OnAudioPageClosed();
	void OnBrightnessPageClose();
	void OnCameraPageClose();
	void OnConsentPageClose();
	void OnConsentSelectPageClose();
	void OnGamePageClosed();
	void OnGraphicPageClose();
	void OnKeyAssignPageClose();
	void OnLanguagePageClose();
	void OnNetworkPageClose();
	void OnNoSelectReturnToTitle(bool bInNoSelectReturnToTitle);
	void OnOperationTopPageClose();
	void OnSetCurrentAudioCultureCompleted(bool bSucceeded);
	void OpenAccessibilityPage();
	void OpenAnalyticsPage();
	void OpenAudioPage();
	void OpenBrightnessPage();
	void OpenCameraPage();
	void OpenConsentPage(const struct FConfigurationConsentTypeTags& InConsentTag);
	void OpenConsentSelectPage();
	void OpenGamePage();
	void OpenGraphicPage();
	void OpenKeyAssignPage();
	void OpenLanguagePage();
	void OpenNetWorkPage();
	void OpenOperationTopPage();
	void SetTransitType(const struct FConfigurationTransitTypeTags& InTransitTag);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_ConfigurationUIObject_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_ConfigurationUIObject_C")
	}
	static class UBP_ConfigurationUIObject_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_ConfigurationUIObject_C>();
	}
};
DUMPER7_ASSERTS_UBP_ConfigurationUIObject_C;

}

