#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MotorcycleVisualControl

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "Extensions_structs.hpp"
#include "BP_MountVisualControl_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_MotorcycleVisualControl.BP_MotorcycleVisualControl_C
// 0x0210 (0x05C0 - 0x03B0)
class UBP_MotorcycleVisualControl_C final : public UBP_MountVisualControl_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_MotorcycleVisualControl_C;       // 0x03A8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UNiagaraSystem*                         VanishGadgetEffect_Asset;                          // 0x03B0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UBP_VanishGadgetEffect_C*               VanishGadgetEffect;                                // 0x03B8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   WheelMotionBlurMesh_F;                             // 0x03C0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   WheelMotionBlurMesh_R;                             // 0x03C8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UStaticMesh*                            WheelMotionBlurMesh_F_Asset;                       // 0x03D0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UStaticMesh*                            WheelMotionBlurMesh_R_Asset;                       // 0x03D8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class FName                                   WheelMotionBlurMesh_F_AttachSocketName;            // 0x03E0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   WheelMotionBlurMesh_R_AttachSocketName;            // 0x03E8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         WheelMotionBlurMesh_CustomStencilValue;            // 0x03F0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bGliding;                                          // 0x03F4(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3F5[0x3];                                      // 0x03F5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        Wing_Vanish_TotalDuration;                         // 0x03F8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UNiagaraSystem*                         Wing_VanishBodyEffect_Asset;                       // 0x0400(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UBP_VanishBodyEffect_C*                 Wing_VanishBodyEffect;                             // 0x0408(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UNiagaraSystem*                         Wing_AppearLineEffect_Asset;                       // 0x0410(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UNiagaraComponent*                      Wing_AppearLineEffect;                             // 0x0418(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          Wing_Appear;                                       // 0x0420(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_421[0x7];                                      // 0x0421(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        Wing_AppearTime;                                   // 0x0428(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Wing_AppearTimeRange;                              // 0x0430(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UNiagaraSystem*                         Wing_VanishGadgetEffect_Asset;                     // 0x0438(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UBP_VanishGadgetEffect_C*               Wing_VanishGadgetEffect;                           // 0x0440(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	bool                                          Wing_Disappear;                                    // 0x0448(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_449[0x7];                                      // 0x0449(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        Wing_DisappearTimeRange;                           // 0x0450(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMountDamageComponent*                  DamageComponent;                                   // 0x0458(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	double                                        DamageWeight_Current;                              // 0x0460(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        DamageWeight_Ratio;                                // 0x0468(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UNiagaraSystem*                         Glid_WingLineEffect_Asset;                         // 0x0470(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UNiagaraComponent*                      Glid_WingLineEffect;                               // 0x0478(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          bSpeedEffect;                                      // 0x0480(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_481[0x7];                                      // 0x0481(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UNiagaraSystem*                         SpeedEffect_LineEffect_Asset;                      // 0x0488(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UNiagaraComponent*                      SpeedEffect_LineEffect;                            // 0x0490(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FRuntimeFloatCurve                     SpeedEffect_SpeedWeightCurve;                      // 0x0498(0x0088)(Edit, BlueprintVisible, DisableEditOnInstance)
	double                                        SpeedEffect_MaxSpeed;                              // 0x0520(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         SpeedEffect_FrontOffset;                           // 0x0528(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_52C[0x4];                                      // 0x052C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FDynamicPostProcessHandle              SpeedEffect_RadialBlurHandle;                      // 0x0530(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	struct FVector                                SpeedEffect_BlurCenter_Pre;                        // 0x0538(0x0018)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bSpeedEffect_Begin;                                // 0x0550(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_551[0x7];                                      // 0x0551(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        DamageWeight_OtherDamageWeigth;                    // 0x0558(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UNiagaraSystem*                         DamageEffect_Asset;                                // 0x0560(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UNiagaraComponent*                      DamageEffect;                                      // 0x0568(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UMaterialInterface*                     SpeedEffect_Material_Asset;                        // 0x0570(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	TArray<class FName>                           WingMaterialArray;                                 // 0x0578(0x0010)(Edit, BlueprintVisible)
	double                                        SpeedEffect_ScreenMask_Radius;                     // 0x0588(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UNiagaraComponent*                      NoMount_Effect;                                    // 0x0590(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	float                                         NoMount_WallSize;                                  // 0x0598(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_59C[0x4];                                      // 0x059C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        DisappearMount_TimeRange_Current;                  // 0x05A0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        DisappearMount_TimeRange_Crash;                    // 0x05A8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        DisappearMount_TimeRange_Normal;                   // 0x05B0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void Damage_Destroy();
	void Damage_OnTick(double DeltaSeconds);
	void Destroy();
	void ExecuteUbergraph_BP_MotorcycleVisualControl(int32 EntryPoint);
	void GetMotorcycle(class ABP_Motorcycle_C** Result);
	void Glide_DeactivateWingLineEffect();
	void Glide_Destroy();
	void Glide_DestroyWingLineEffect();
	void Glide_Initialize();
	void Glide_OnTick(double DeltaSeconds);
	void Glide_SpawnWingLineEffect();
	void Initialize();
	void NoMount_DestroyWall();
	void NoMount_SpawnWall(const struct FHitResult& InHitResult);
	void OnAppearMount();
	void OnAppearWing();
	void OnChangeGlide(bool bGlide);
	void OnDisappearMount(EUnsummonReason Reason_0);
	void OnDisappearMount_EffectFinished(class UNiagaraComponent* PSystem);
	void OnDisappearWIng();
	void OnNoMount(const struct FHitResult& InHitResult);
	bool OnSimpleAnimNotify_Begin(class UObject* InAnimNotifyObject, class UAnimSequenceBase* InAnimSequence, const class FName& InMessage, float InTotalDuration);
	bool OnSimpleAnimNotify_End(class UObject* InAnimNotifyObject, class UAnimSequenceBase* InAnimSequence, const class FName& InMessage);
	bool OnSimpleAnimNotify_Tick(class UObject* InAnimNotifyObject, class UAnimSequenceBase* InAnimSequence, const class FName& InMessage, float InDeltaTime);
	void OnTick(double DeltaSeconds);
	void OverrideWheelTrackDecal(struct FDecalSpawnParameters* OutSpawnInfo, const struct FDecalSpawnParameters& InSpawnInfo, const struct FVector& LastSpawnedLocation);
	void ReceiveEndPlay(EEndPlayReason EndPlayReason);
	void ReceiveTick(float DeltaSeconds);
	void SetDisappearMode(EUnsummonReason Reason_0);
	void SpeedEffect_CreateEffect();
	void SpeedEffect_CreatePostProcess();
	void SpeedEffect_DeactivateEffect();
	void SpeedEffect_Destroy();
	void SpeedEffect_DestroyEffect();
	void SpeedEffect_DestroyPostProcess();
	void SpeedEffect_Initialize();
	void SpeedEffect_OnTick(double DeltaSeconds);
	void WheelMotionBlur_Destroy();
	void WheelMotionBlur_Initialize();
	void WheelMotionBlur_Initialize_Mesh(class UStaticMesh* MeshAsset, class FName AttachSocketName, class UStaticMeshComponent** Result);
	void WheelMotionBlur_Tick(double DeltaSeconds);
	void WheelMotionBlur_Tick_Mesh(double DeltaSeconds, class UStaticMeshComponent* BlurMesh, int32 WheelIndex, double* AngleSpeed);
	void Wing_AppearBegin();
	void Wing_AppearEnd();
	void Wing_DisappearEnd();
	void Wing_OnAppearTick(float DeltaSeconds);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_MotorcycleVisualControl_C">();
	}
	static class UBP_MotorcycleVisualControl_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_MotorcycleVisualControl_C>();
	}
};
static_assert(alignof(UBP_MotorcycleVisualControl_C) == 0x000010, "Wrong alignment on UBP_MotorcycleVisualControl_C");
static_assert(sizeof(UBP_MotorcycleVisualControl_C) == 0x0005C0, "Wrong size on UBP_MotorcycleVisualControl_C");
static_assert(offsetof(UBP_MotorcycleVisualControl_C, UberGraphFrame_BP_MotorcycleVisualControl_C) == 0x0003A8, "Member 'UBP_MotorcycleVisualControl_C::UberGraphFrame_BP_MotorcycleVisualControl_C' has a wrong offset!");
static_assert(offsetof(UBP_MotorcycleVisualControl_C, VanishGadgetEffect_Asset) == 0x0003B0, "Member 'UBP_MotorcycleVisualControl_C::VanishGadgetEffect_Asset' has a wrong offset!");
static_assert(offsetof(UBP_MotorcycleVisualControl_C, VanishGadgetEffect) == 0x0003B8, "Member 'UBP_MotorcycleVisualControl_C::VanishGadgetEffect' has a wrong offset!");
static_assert(offsetof(UBP_MotorcycleVisualControl_C, WheelMotionBlurMesh_F) == 0x0003C0, "Member 'UBP_MotorcycleVisualControl_C::WheelMotionBlurMesh_F' has a wrong offset!");
static_assert(offsetof(UBP_MotorcycleVisualControl_C, WheelMotionBlurMesh_R) == 0x0003C8, "Member 'UBP_MotorcycleVisualControl_C::WheelMotionBlurMesh_R' has a wrong offset!");
static_assert(offsetof(UBP_MotorcycleVisualControl_C, WheelMotionBlurMesh_F_Asset) == 0x0003D0, "Member 'UBP_MotorcycleVisualControl_C::WheelMotionBlurMesh_F_Asset' has a wrong offset!");
static_assert(offsetof(UBP_MotorcycleVisualControl_C, WheelMotionBlurMesh_R_Asset) == 0x0003D8, "Member 'UBP_MotorcycleVisualControl_C::WheelMotionBlurMesh_R_Asset' has a wrong offset!");
static_assert(offsetof(UBP_MotorcycleVisualControl_C, WheelMotionBlurMesh_F_AttachSocketName) == 0x0003E0, "Member 'UBP_MotorcycleVisualControl_C::WheelMotionBlurMesh_F_AttachSocketName' has a wrong offset!");
static_assert(offsetof(UBP_MotorcycleVisualControl_C, WheelMotionBlurMesh_R_AttachSocketName) == 0x0003E8, "Member 'UBP_MotorcycleVisualControl_C::WheelMotionBlurMesh_R_AttachSocketName' has a wrong offset!");
static_assert(offsetof(UBP_MotorcycleVisualControl_C, WheelMotionBlurMesh_CustomStencilValue) == 0x0003F0, "Member 'UBP_MotorcycleVisualControl_C::WheelMotionBlurMesh_CustomStencilValue' has a wrong offset!");
static_assert(offsetof(UBP_MotorcycleVisualControl_C, bGliding) == 0x0003F4, "Member 'UBP_MotorcycleVisualControl_C::bGliding' has a wrong offset!");
static_assert(offsetof(UBP_MotorcycleVisualControl_C, Wing_Vanish_TotalDuration) == 0x0003F8, "Member 'UBP_MotorcycleVisualControl_C::Wing_Vanish_TotalDuration' has a wrong offset!");
static_assert(offsetof(UBP_MotorcycleVisualControl_C, Wing_VanishBodyEffect_Asset) == 0x000400, "Member 'UBP_MotorcycleVisualControl_C::Wing_VanishBodyEffect_Asset' has a wrong offset!");
static_assert(offsetof(UBP_MotorcycleVisualControl_C, Wing_VanishBodyEffect) == 0x000408, "Member 'UBP_MotorcycleVisualControl_C::Wing_VanishBodyEffect' has a wrong offset!");
static_assert(offsetof(UBP_MotorcycleVisualControl_C, Wing_AppearLineEffect_Asset) == 0x000410, "Member 'UBP_MotorcycleVisualControl_C::Wing_AppearLineEffect_Asset' has a wrong offset!");
static_assert(offsetof(UBP_MotorcycleVisualControl_C, Wing_AppearLineEffect) == 0x000418, "Member 'UBP_MotorcycleVisualControl_C::Wing_AppearLineEffect' has a wrong offset!");
static_assert(offsetof(UBP_MotorcycleVisualControl_C, Wing_Appear) == 0x000420, "Member 'UBP_MotorcycleVisualControl_C::Wing_Appear' has a wrong offset!");
static_assert(offsetof(UBP_MotorcycleVisualControl_C, Wing_AppearTime) == 0x000428, "Member 'UBP_MotorcycleVisualControl_C::Wing_AppearTime' has a wrong offset!");
static_assert(offsetof(UBP_MotorcycleVisualControl_C, Wing_AppearTimeRange) == 0x000430, "Member 'UBP_MotorcycleVisualControl_C::Wing_AppearTimeRange' has a wrong offset!");
static_assert(offsetof(UBP_MotorcycleVisualControl_C, Wing_VanishGadgetEffect_Asset) == 0x000438, "Member 'UBP_MotorcycleVisualControl_C::Wing_VanishGadgetEffect_Asset' has a wrong offset!");
static_assert(offsetof(UBP_MotorcycleVisualControl_C, Wing_VanishGadgetEffect) == 0x000440, "Member 'UBP_MotorcycleVisualControl_C::Wing_VanishGadgetEffect' has a wrong offset!");
static_assert(offsetof(UBP_MotorcycleVisualControl_C, Wing_Disappear) == 0x000448, "Member 'UBP_MotorcycleVisualControl_C::Wing_Disappear' has a wrong offset!");
static_assert(offsetof(UBP_MotorcycleVisualControl_C, Wing_DisappearTimeRange) == 0x000450, "Member 'UBP_MotorcycleVisualControl_C::Wing_DisappearTimeRange' has a wrong offset!");
static_assert(offsetof(UBP_MotorcycleVisualControl_C, DamageComponent) == 0x000458, "Member 'UBP_MotorcycleVisualControl_C::DamageComponent' has a wrong offset!");
static_assert(offsetof(UBP_MotorcycleVisualControl_C, DamageWeight_Current) == 0x000460, "Member 'UBP_MotorcycleVisualControl_C::DamageWeight_Current' has a wrong offset!");
static_assert(offsetof(UBP_MotorcycleVisualControl_C, DamageWeight_Ratio) == 0x000468, "Member 'UBP_MotorcycleVisualControl_C::DamageWeight_Ratio' has a wrong offset!");
static_assert(offsetof(UBP_MotorcycleVisualControl_C, Glid_WingLineEffect_Asset) == 0x000470, "Member 'UBP_MotorcycleVisualControl_C::Glid_WingLineEffect_Asset' has a wrong offset!");
static_assert(offsetof(UBP_MotorcycleVisualControl_C, Glid_WingLineEffect) == 0x000478, "Member 'UBP_MotorcycleVisualControl_C::Glid_WingLineEffect' has a wrong offset!");
static_assert(offsetof(UBP_MotorcycleVisualControl_C, bSpeedEffect) == 0x000480, "Member 'UBP_MotorcycleVisualControl_C::bSpeedEffect' has a wrong offset!");
static_assert(offsetof(UBP_MotorcycleVisualControl_C, SpeedEffect_LineEffect_Asset) == 0x000488, "Member 'UBP_MotorcycleVisualControl_C::SpeedEffect_LineEffect_Asset' has a wrong offset!");
static_assert(offsetof(UBP_MotorcycleVisualControl_C, SpeedEffect_LineEffect) == 0x000490, "Member 'UBP_MotorcycleVisualControl_C::SpeedEffect_LineEffect' has a wrong offset!");
static_assert(offsetof(UBP_MotorcycleVisualControl_C, SpeedEffect_SpeedWeightCurve) == 0x000498, "Member 'UBP_MotorcycleVisualControl_C::SpeedEffect_SpeedWeightCurve' has a wrong offset!");
static_assert(offsetof(UBP_MotorcycleVisualControl_C, SpeedEffect_MaxSpeed) == 0x000520, "Member 'UBP_MotorcycleVisualControl_C::SpeedEffect_MaxSpeed' has a wrong offset!");
static_assert(offsetof(UBP_MotorcycleVisualControl_C, SpeedEffect_FrontOffset) == 0x000528, "Member 'UBP_MotorcycleVisualControl_C::SpeedEffect_FrontOffset' has a wrong offset!");
static_assert(offsetof(UBP_MotorcycleVisualControl_C, SpeedEffect_RadialBlurHandle) == 0x000530, "Member 'UBP_MotorcycleVisualControl_C::SpeedEffect_RadialBlurHandle' has a wrong offset!");
static_assert(offsetof(UBP_MotorcycleVisualControl_C, SpeedEffect_BlurCenter_Pre) == 0x000538, "Member 'UBP_MotorcycleVisualControl_C::SpeedEffect_BlurCenter_Pre' has a wrong offset!");
static_assert(offsetof(UBP_MotorcycleVisualControl_C, bSpeedEffect_Begin) == 0x000550, "Member 'UBP_MotorcycleVisualControl_C::bSpeedEffect_Begin' has a wrong offset!");
static_assert(offsetof(UBP_MotorcycleVisualControl_C, DamageWeight_OtherDamageWeigth) == 0x000558, "Member 'UBP_MotorcycleVisualControl_C::DamageWeight_OtherDamageWeigth' has a wrong offset!");
static_assert(offsetof(UBP_MotorcycleVisualControl_C, DamageEffect_Asset) == 0x000560, "Member 'UBP_MotorcycleVisualControl_C::DamageEffect_Asset' has a wrong offset!");
static_assert(offsetof(UBP_MotorcycleVisualControl_C, DamageEffect) == 0x000568, "Member 'UBP_MotorcycleVisualControl_C::DamageEffect' has a wrong offset!");
static_assert(offsetof(UBP_MotorcycleVisualControl_C, SpeedEffect_Material_Asset) == 0x000570, "Member 'UBP_MotorcycleVisualControl_C::SpeedEffect_Material_Asset' has a wrong offset!");
static_assert(offsetof(UBP_MotorcycleVisualControl_C, WingMaterialArray) == 0x000578, "Member 'UBP_MotorcycleVisualControl_C::WingMaterialArray' has a wrong offset!");
static_assert(offsetof(UBP_MotorcycleVisualControl_C, SpeedEffect_ScreenMask_Radius) == 0x000588, "Member 'UBP_MotorcycleVisualControl_C::SpeedEffect_ScreenMask_Radius' has a wrong offset!");
static_assert(offsetof(UBP_MotorcycleVisualControl_C, NoMount_Effect) == 0x000590, "Member 'UBP_MotorcycleVisualControl_C::NoMount_Effect' has a wrong offset!");
static_assert(offsetof(UBP_MotorcycleVisualControl_C, NoMount_WallSize) == 0x000598, "Member 'UBP_MotorcycleVisualControl_C::NoMount_WallSize' has a wrong offset!");
static_assert(offsetof(UBP_MotorcycleVisualControl_C, DisappearMount_TimeRange_Current) == 0x0005A0, "Member 'UBP_MotorcycleVisualControl_C::DisappearMount_TimeRange_Current' has a wrong offset!");
static_assert(offsetof(UBP_MotorcycleVisualControl_C, DisappearMount_TimeRange_Crash) == 0x0005A8, "Member 'UBP_MotorcycleVisualControl_C::DisappearMount_TimeRange_Crash' has a wrong offset!");
static_assert(offsetof(UBP_MotorcycleVisualControl_C, DisappearMount_TimeRange_Normal) == 0x0005B0, "Member 'UBP_MotorcycleVisualControl_C::DisappearMount_TimeRange_Normal' has a wrong offset!");

}

