#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MapMenuUIObject

#include "Basic.hpp"

#include "GameplayTags_structs.hpp"


namespace SDK::Params
{

// Function BP_MapMenuUIObject.BP_MapMenuUIObject_C.Close
// 0x0002 (0x0002 - 0x0000)
struct BP_MapMenuUIObject_C_Close final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Close_ReturnValue;                        // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_MapMenuUIObject_C_Close) == 0x000001, "Wrong alignment on BP_MapMenuUIObject_C_Close");
static_assert(sizeof(BP_MapMenuUIObject_C_Close) == 0x000002, "Wrong size on BP_MapMenuUIObject_C_Close");
static_assert(offsetof(BP_MapMenuUIObject_C_Close, ReturnValue) == 0x000000, "Member 'BP_MapMenuUIObject_C_Close::ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MapMenuUIObject_C_Close, CallFunc_Close_ReturnValue) == 0x000001, "Member 'BP_MapMenuUIObject_C_Close::CallFunc_Close_ReturnValue' has a wrong offset!");

// Function BP_MapMenuUIObject.BP_MapMenuUIObject_C.NotifyFastTravelProhibited
// 0x0028 (0x0028 - 0x0000)
struct BP_MapMenuUIObject_C_NotifyFastTravelProhibited final
{
public:
	bool                                          InEnabled;                                         // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          ReturnValue;                                       // 0x0001(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2[0x6];                                        // 0x0002(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UMenuBase*                              CallFunc_GetTopMenu_ReturnValue;                   // 0x0008(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UWDT_MapMenu_C*                         K2Node_DynamicCast_AsWDT_Map_Menu;                 // 0x0018(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_MapMenuUIObject_C_NotifyFastTravelProhibited) == 0x000008, "Wrong alignment on BP_MapMenuUIObject_C_NotifyFastTravelProhibited");
static_assert(sizeof(BP_MapMenuUIObject_C_NotifyFastTravelProhibited) == 0x000028, "Wrong size on BP_MapMenuUIObject_C_NotifyFastTravelProhibited");
static_assert(offsetof(BP_MapMenuUIObject_C_NotifyFastTravelProhibited, InEnabled) == 0x000000, "Member 'BP_MapMenuUIObject_C_NotifyFastTravelProhibited::InEnabled' has a wrong offset!");
static_assert(offsetof(BP_MapMenuUIObject_C_NotifyFastTravelProhibited, ReturnValue) == 0x000001, "Member 'BP_MapMenuUIObject_C_NotifyFastTravelProhibited::ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MapMenuUIObject_C_NotifyFastTravelProhibited, CallFunc_GetTopMenu_ReturnValue) == 0x000008, "Member 'BP_MapMenuUIObject_C_NotifyFastTravelProhibited::CallFunc_GetTopMenu_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MapMenuUIObject_C_NotifyFastTravelProhibited, CallFunc_IsValid_ReturnValue) == 0x000010, "Member 'BP_MapMenuUIObject_C_NotifyFastTravelProhibited::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MapMenuUIObject_C_NotifyFastTravelProhibited, K2Node_DynamicCast_AsWDT_Map_Menu) == 0x000018, "Member 'BP_MapMenuUIObject_C_NotifyFastTravelProhibited::K2Node_DynamicCast_AsWDT_Map_Menu' has a wrong offset!");
static_assert(offsetof(BP_MapMenuUIObject_C_NotifyFastTravelProhibited, K2Node_DynamicCast_bSuccess) == 0x000020, "Member 'BP_MapMenuUIObject_C_NotifyFastTravelProhibited::K2Node_DynamicCast_bSuccess' has a wrong offset!");

// Function BP_MapMenuUIObject.BP_MapMenuUIObject_C.Open
// 0x0002 (0x0002 - 0x0000)
struct BP_MapMenuUIObject_C_Open final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Open_ReturnValue;                         // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_MapMenuUIObject_C_Open) == 0x000001, "Wrong alignment on BP_MapMenuUIObject_C_Open");
static_assert(sizeof(BP_MapMenuUIObject_C_Open) == 0x000002, "Wrong size on BP_MapMenuUIObject_C_Open");
static_assert(offsetof(BP_MapMenuUIObject_C_Open, ReturnValue) == 0x000000, "Member 'BP_MapMenuUIObject_C_Open::ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MapMenuUIObject_C_Open, CallFunc_Open_ReturnValue) == 0x000001, "Member 'BP_MapMenuUIObject_C_Open::CallFunc_Open_ReturnValue' has a wrong offset!");

// Function BP_MapMenuUIObject.BP_MapMenuUIObject_C.SetSelectFeature
// 0x0028 (0x0028 - 0x0000)
struct BP_MapMenuUIObject_C_SetSelectFeature final
{
public:
	struct FGameplayTag                           InFeatureId;                                       // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
	class FName                                   InSelectLouDiaryID;                                // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMenuBase*                              CallFunc_GetTopMenu_ReturnValue;                   // 0x0010(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UWDT_MapMenu_C*                         K2Node_DynamicCast_AsWDT_Map_Menu;                 // 0x0018(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0021(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_MapMenuUIObject_C_SetSelectFeature) == 0x000008, "Wrong alignment on BP_MapMenuUIObject_C_SetSelectFeature");
static_assert(sizeof(BP_MapMenuUIObject_C_SetSelectFeature) == 0x000028, "Wrong size on BP_MapMenuUIObject_C_SetSelectFeature");
static_assert(offsetof(BP_MapMenuUIObject_C_SetSelectFeature, InFeatureId) == 0x000000, "Member 'BP_MapMenuUIObject_C_SetSelectFeature::InFeatureId' has a wrong offset!");
static_assert(offsetof(BP_MapMenuUIObject_C_SetSelectFeature, InSelectLouDiaryID) == 0x000008, "Member 'BP_MapMenuUIObject_C_SetSelectFeature::InSelectLouDiaryID' has a wrong offset!");
static_assert(offsetof(BP_MapMenuUIObject_C_SetSelectFeature, CallFunc_GetTopMenu_ReturnValue) == 0x000010, "Member 'BP_MapMenuUIObject_C_SetSelectFeature::CallFunc_GetTopMenu_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MapMenuUIObject_C_SetSelectFeature, K2Node_DynamicCast_AsWDT_Map_Menu) == 0x000018, "Member 'BP_MapMenuUIObject_C_SetSelectFeature::K2Node_DynamicCast_AsWDT_Map_Menu' has a wrong offset!");
static_assert(offsetof(BP_MapMenuUIObject_C_SetSelectFeature, K2Node_DynamicCast_bSuccess) == 0x000020, "Member 'BP_MapMenuUIObject_C_SetSelectFeature::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_MapMenuUIObject_C_SetSelectFeature, CallFunc_IsValid_ReturnValue) == 0x000021, "Member 'BP_MapMenuUIObject_C_SetSelectFeature::CallFunc_IsValid_ReturnValue' has a wrong offset!");

}

