#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PickupItem

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "StoryFlagSystem_structs.hpp"
#include "Extensions_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_PickupItem.BP_PickupItem_C
// 0x0038 (0x0528 - 0x04F0)
class ABP_PickupItem_C : public APickupItem
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x04F0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UInteractionMarkerComponent*            InteractionMarker;                                 // 0x04F8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBillboardComponent*                    Billboard;                                         // 0x0500(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UNiagaraSystem*                         NiagaraSystem_Common;                              // 0x0508(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UNiagaraSystem*                         NiagaraSystem_Rare;                                // 0x0510(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UNiagaraSystem*                         NiagaraSystem_Legendary;                           // 0x0518(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FStoryFlagLabel                        PickedFlag;                                        // 0x0520(0x0008)(Edit, BlueprintVisible, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_PickupItem(int32 EntryPoint);
	void OnInteractionEnd_BP(class AActor* InActor);
	void UpdateHiddenByGameFlag_BP(const bool bShouldHide);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_PickupItem_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_PickupItem_C")
	}
	static class ABP_PickupItem_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_PickupItem_C>();
	}
};
DUMPER7_ASSERTS_ABP_PickupItem_C;

}

