#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SmallScenario_Noah_Present_c01040

#include "Basic.hpp"

#include "BP_SmallScenario_Noah_Present_c01040_classes.hpp"
#include "BP_SmallScenario_Noah_Present_c01040_parameters.hpp"


namespace SDK
{

// Function BP_SmallScenario_Noah_Present_c01040.BP_SmallScenario_Noah_Present_c01040_C.Abort
// (BlueprintCallable, BlueprintEvent)

void ABP_SmallScenario_Noah_Present_c01040_C::Abort()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SmallScenario_Noah_Present_c01040_C", "Abort");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SmallScenario_Noah_Present_c01040.BP_SmallScenario_Noah_Present_c01040_C.Complete
// (BlueprintCallable, BlueprintEvent)

void ABP_SmallScenario_Noah_Present_c01040_C::Complete()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SmallScenario_Noah_Present_c01040_C", "Complete");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SmallScenario_Noah_Present_c01040.BP_SmallScenario_Noah_Present_c01040_C.End
// (BlueprintCallable, BlueprintEvent)

void ABP_SmallScenario_Noah_Present_c01040_C::End()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SmallScenario_Noah_Present_c01040_C", "End");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SmallScenario_Noah_Present_c01040.BP_SmallScenario_Noah_Present_c01040_C.ExecuteUbergraph_BP_SmallScenario_Noah_Present_c01040
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_SmallScenario_Noah_Present_c01040_C::ExecuteUbergraph_BP_SmallScenario_Noah_Present_c01040(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SmallScenario_Noah_Present_c01040_C", "ExecuteUbergraph_BP_SmallScenario_Noah_Present_c01040");

	Params::BP_SmallScenario_Noah_Present_c01040_C_ExecuteUbergraph_BP_SmallScenario_Noah_Present_c01040 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SmallScenario_Noah_Present_c01040.BP_SmallScenario_Noah_Present_c01040_C.Start
// (BlueprintCallable, BlueprintEvent)

void ABP_SmallScenario_Noah_Present_c01040_C::Start()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SmallScenario_Noah_Present_c01040_C", "Start");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SmallScenario_Noah_Present_c01040.BP_SmallScenario_Noah_Present_c01040_C.StartScenario
// (BlueprintCallable, BlueprintEvent)

void ABP_SmallScenario_Noah_Present_c01040_C::StartScenario()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SmallScenario_Noah_Present_c01040_C", "StartScenario");

	UObject::ProcessEvent(Func, nullptr);
}

}

