#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SmallScenario_TestSpecialRetroGame

#include "Basic.hpp"

#include "BP_SmallScenario_TestSpecialRetroGame_classes.hpp"
#include "BP_SmallScenario_TestSpecialRetroGame_parameters.hpp"


namespace SDK
{

// Function BP_SmallScenario_TestSpecialRetroGame.BP_SmallScenario_TestSpecialRetroGame_C.Abort
// (BlueprintCallable, BlueprintEvent)

void ABP_SmallScenario_TestSpecialRetroGame_C::Abort()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SmallScenario_TestSpecialRetroGame_C", "Abort");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SmallScenario_TestSpecialRetroGame.BP_SmallScenario_TestSpecialRetroGame_C.Complete
// (BlueprintCallable, BlueprintEvent)

void ABP_SmallScenario_TestSpecialRetroGame_C::Complete()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SmallScenario_TestSpecialRetroGame_C", "Complete");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SmallScenario_TestSpecialRetroGame.BP_SmallScenario_TestSpecialRetroGame_C.End
// (BlueprintCallable, BlueprintEvent)

void ABP_SmallScenario_TestSpecialRetroGame_C::End()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SmallScenario_TestSpecialRetroGame_C", "End");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SmallScenario_TestSpecialRetroGame.BP_SmallScenario_TestSpecialRetroGame_C.ExecuteUbergraph_BP_SmallScenario_TestSpecialRetroGame
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_SmallScenario_TestSpecialRetroGame_C::ExecuteUbergraph_BP_SmallScenario_TestSpecialRetroGame(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SmallScenario_TestSpecialRetroGame_C", "ExecuteUbergraph_BP_SmallScenario_TestSpecialRetroGame");

	Params::BP_SmallScenario_TestSpecialRetroGame_C_ExecuteUbergraph_BP_SmallScenario_TestSpecialRetroGame Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SmallScenario_TestSpecialRetroGame.BP_SmallScenario_TestSpecialRetroGame_C.Start
// (BlueprintCallable, BlueprintEvent)

void ABP_SmallScenario_TestSpecialRetroGame_C::Start()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SmallScenario_TestSpecialRetroGame_C", "Start");

	UObject::ProcessEvent(Func, nullptr);
}

}

