#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SupportMenuItemDataBase

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_SupportMenuItemDataBase.BP_SupportMenuItemDataBase_C
// 0x0038 (0x0060 - 0x0028)
class UBP_SupportMenuItemDataBase_C : public UObject
{
public:
	FMulticastInlineDelegateProperty_             OnChangeExpansion;                                 // 0x0028(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	bool                                          bIsCategory;                                       // 0x0038(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	bool                                          bIsExpansion;                                      // 0x0039(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3A[0x2];                                       // 0x003A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   ItemKeyName;                                       // 0x003C(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	bool                                          DisplayNewFlag;                                    // 0x0044(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_45[0x3];                                       // 0x0045(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	FMulticastInlineDelegateProperty_             OnChangeNewFlag;                                   // 0x0048(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	bool                                          IsQuestClear;                                      // 0x0058(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bFeatureIconVisibility;                            // 0x0059(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bFeatureIconGrayOut;                               // 0x005A(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bIsFeatureReleased;                                // 0x005B(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bIsQuestDeactivate;                                // 0x005C(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void SetIsQuestDeactivate(bool bInIsQuestDisable);
	void SetIsQuestClear(bool IsEnable);
	void SetIsFeatureReleased(bool bInIsFeatureReleased);
	void SetIsFeatureIconVisibility(bool InVisible);
	void SetIsFeatureIconGrayOut(bool InGrayOut);
	void SetIsExpansion(bool InFlag);
	void SetDisplayNewFlag(bool InFlag);
	void OnChangeNewFlag__DelegateSignature(bool InIsNew);
	void OnChangeExpansion__DelegateSignature(bool InIsExpansion);
	void GetTitleText(class FText* OutText);
	void GetTexture(TSoftObjectPtr<class UTexture2D>* OutTexture);
	void GetItemKeyName(class FName* OutKeyName);
	void GetIsQuestDeactivate(bool* bOutIsQuestDisable);
	void GetIsQuestClear(bool* IsEnable);
	void GetIsFeatureReleased(bool* OutIsFeatureReleased);
	void GetIsFeatureIconVisibility(bool* OutVisibility);
	void GetIsFeatureIconGrayOut(bool* OutGrayOut);
	void GetIsExpansion(bool* OutFlag);
	void GetIsCategory(bool* OutIsCategory);
	void GetDisplayNewFlag(bool* OutFlag);
	void GetDescriptionTextFinished(class FText* OutText);
	void GetDescriptionText(class FText* OutText);
	void GetCategoryKeyList(TArray<class FName>* OutCategoryList);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_SupportMenuItemDataBase_C">();
	}
	static class UBP_SupportMenuItemDataBase_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_SupportMenuItemDataBase_C>();
	}
};
static_assert(alignof(UBP_SupportMenuItemDataBase_C) == 0x000008, "Wrong alignment on UBP_SupportMenuItemDataBase_C");
static_assert(sizeof(UBP_SupportMenuItemDataBase_C) == 0x000060, "Wrong size on UBP_SupportMenuItemDataBase_C");
static_assert(offsetof(UBP_SupportMenuItemDataBase_C, OnChangeExpansion) == 0x000028, "Member 'UBP_SupportMenuItemDataBase_C::OnChangeExpansion' has a wrong offset!");
static_assert(offsetof(UBP_SupportMenuItemDataBase_C, bIsCategory) == 0x000038, "Member 'UBP_SupportMenuItemDataBase_C::bIsCategory' has a wrong offset!");
static_assert(offsetof(UBP_SupportMenuItemDataBase_C, bIsExpansion) == 0x000039, "Member 'UBP_SupportMenuItemDataBase_C::bIsExpansion' has a wrong offset!");
static_assert(offsetof(UBP_SupportMenuItemDataBase_C, ItemKeyName) == 0x00003C, "Member 'UBP_SupportMenuItemDataBase_C::ItemKeyName' has a wrong offset!");
static_assert(offsetof(UBP_SupportMenuItemDataBase_C, DisplayNewFlag) == 0x000044, "Member 'UBP_SupportMenuItemDataBase_C::DisplayNewFlag' has a wrong offset!");
static_assert(offsetof(UBP_SupportMenuItemDataBase_C, OnChangeNewFlag) == 0x000048, "Member 'UBP_SupportMenuItemDataBase_C::OnChangeNewFlag' has a wrong offset!");
static_assert(offsetof(UBP_SupportMenuItemDataBase_C, IsQuestClear) == 0x000058, "Member 'UBP_SupportMenuItemDataBase_C::IsQuestClear' has a wrong offset!");
static_assert(offsetof(UBP_SupportMenuItemDataBase_C, bFeatureIconVisibility) == 0x000059, "Member 'UBP_SupportMenuItemDataBase_C::bFeatureIconVisibility' has a wrong offset!");
static_assert(offsetof(UBP_SupportMenuItemDataBase_C, bFeatureIconGrayOut) == 0x00005A, "Member 'UBP_SupportMenuItemDataBase_C::bFeatureIconGrayOut' has a wrong offset!");
static_assert(offsetof(UBP_SupportMenuItemDataBase_C, bIsFeatureReleased) == 0x00005B, "Member 'UBP_SupportMenuItemDataBase_C::bIsFeatureReleased' has a wrong offset!");
static_assert(offsetof(UBP_SupportMenuItemDataBase_C, bIsQuestDeactivate) == 0x00005C, "Member 'UBP_SupportMenuItemDataBase_C::bIsQuestDeactivate' has a wrong offset!");

}

