#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SupportMenuItemDataBase

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_SupportMenuItemDataBase.BP_SupportMenuItemDataBase_C.SetIsQuestDeactivate
// 0x0001 (0x0001 - 0x0000)
struct BP_SupportMenuItemDataBase_C_SetIsQuestDeactivate final
{
public:
	bool                                          bInIsQuestDisable;                                 // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_SupportMenuItemDataBase_C_SetIsQuestDeactivate) == 0x000001, "Wrong alignment on BP_SupportMenuItemDataBase_C_SetIsQuestDeactivate");
static_assert(sizeof(BP_SupportMenuItemDataBase_C_SetIsQuestDeactivate) == 0x000001, "Wrong size on BP_SupportMenuItemDataBase_C_SetIsQuestDeactivate");
static_assert(offsetof(BP_SupportMenuItemDataBase_C_SetIsQuestDeactivate, bInIsQuestDisable) == 0x000000, "Member 'BP_SupportMenuItemDataBase_C_SetIsQuestDeactivate::bInIsQuestDisable' has a wrong offset!");

// Function BP_SupportMenuItemDataBase.BP_SupportMenuItemDataBase_C.SetIsQuestClear
// 0x0001 (0x0001 - 0x0000)
struct BP_SupportMenuItemDataBase_C_SetIsQuestClear final
{
public:
	bool                                          IsEnable;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_SupportMenuItemDataBase_C_SetIsQuestClear) == 0x000001, "Wrong alignment on BP_SupportMenuItemDataBase_C_SetIsQuestClear");
static_assert(sizeof(BP_SupportMenuItemDataBase_C_SetIsQuestClear) == 0x000001, "Wrong size on BP_SupportMenuItemDataBase_C_SetIsQuestClear");
static_assert(offsetof(BP_SupportMenuItemDataBase_C_SetIsQuestClear, IsEnable) == 0x000000, "Member 'BP_SupportMenuItemDataBase_C_SetIsQuestClear::IsEnable' has a wrong offset!");

// Function BP_SupportMenuItemDataBase.BP_SupportMenuItemDataBase_C.SetIsFeatureReleased
// 0x0001 (0x0001 - 0x0000)
struct BP_SupportMenuItemDataBase_C_SetIsFeatureReleased final
{
public:
	bool                                          bInIsFeatureReleased;                              // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_SupportMenuItemDataBase_C_SetIsFeatureReleased) == 0x000001, "Wrong alignment on BP_SupportMenuItemDataBase_C_SetIsFeatureReleased");
static_assert(sizeof(BP_SupportMenuItemDataBase_C_SetIsFeatureReleased) == 0x000001, "Wrong size on BP_SupportMenuItemDataBase_C_SetIsFeatureReleased");
static_assert(offsetof(BP_SupportMenuItemDataBase_C_SetIsFeatureReleased, bInIsFeatureReleased) == 0x000000, "Member 'BP_SupportMenuItemDataBase_C_SetIsFeatureReleased::bInIsFeatureReleased' has a wrong offset!");

// Function BP_SupportMenuItemDataBase.BP_SupportMenuItemDataBase_C.SetIsFeatureIconVisibility
// 0x0001 (0x0001 - 0x0000)
struct BP_SupportMenuItemDataBase_C_SetIsFeatureIconVisibility final
{
public:
	bool                                          InVisible;                                         // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_SupportMenuItemDataBase_C_SetIsFeatureIconVisibility) == 0x000001, "Wrong alignment on BP_SupportMenuItemDataBase_C_SetIsFeatureIconVisibility");
static_assert(sizeof(BP_SupportMenuItemDataBase_C_SetIsFeatureIconVisibility) == 0x000001, "Wrong size on BP_SupportMenuItemDataBase_C_SetIsFeatureIconVisibility");
static_assert(offsetof(BP_SupportMenuItemDataBase_C_SetIsFeatureIconVisibility, InVisible) == 0x000000, "Member 'BP_SupportMenuItemDataBase_C_SetIsFeatureIconVisibility::InVisible' has a wrong offset!");

// Function BP_SupportMenuItemDataBase.BP_SupportMenuItemDataBase_C.SetIsFeatureIconGrayOut
// 0x0001 (0x0001 - 0x0000)
struct BP_SupportMenuItemDataBase_C_SetIsFeatureIconGrayOut final
{
public:
	bool                                          InGrayOut;                                         // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_SupportMenuItemDataBase_C_SetIsFeatureIconGrayOut) == 0x000001, "Wrong alignment on BP_SupportMenuItemDataBase_C_SetIsFeatureIconGrayOut");
static_assert(sizeof(BP_SupportMenuItemDataBase_C_SetIsFeatureIconGrayOut) == 0x000001, "Wrong size on BP_SupportMenuItemDataBase_C_SetIsFeatureIconGrayOut");
static_assert(offsetof(BP_SupportMenuItemDataBase_C_SetIsFeatureIconGrayOut, InGrayOut) == 0x000000, "Member 'BP_SupportMenuItemDataBase_C_SetIsFeatureIconGrayOut::InGrayOut' has a wrong offset!");

// Function BP_SupportMenuItemDataBase.BP_SupportMenuItemDataBase_C.SetIsExpansion
// 0x0001 (0x0001 - 0x0000)
struct BP_SupportMenuItemDataBase_C_SetIsExpansion final
{
public:
	bool                                          InFlag;                                            // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_SupportMenuItemDataBase_C_SetIsExpansion) == 0x000001, "Wrong alignment on BP_SupportMenuItemDataBase_C_SetIsExpansion");
static_assert(sizeof(BP_SupportMenuItemDataBase_C_SetIsExpansion) == 0x000001, "Wrong size on BP_SupportMenuItemDataBase_C_SetIsExpansion");
static_assert(offsetof(BP_SupportMenuItemDataBase_C_SetIsExpansion, InFlag) == 0x000000, "Member 'BP_SupportMenuItemDataBase_C_SetIsExpansion::InFlag' has a wrong offset!");

// Function BP_SupportMenuItemDataBase.BP_SupportMenuItemDataBase_C.SetDisplayNewFlag
// 0x0001 (0x0001 - 0x0000)
struct BP_SupportMenuItemDataBase_C_SetDisplayNewFlag final
{
public:
	bool                                          InFlag;                                            // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_SupportMenuItemDataBase_C_SetDisplayNewFlag) == 0x000001, "Wrong alignment on BP_SupportMenuItemDataBase_C_SetDisplayNewFlag");
static_assert(sizeof(BP_SupportMenuItemDataBase_C_SetDisplayNewFlag) == 0x000001, "Wrong size on BP_SupportMenuItemDataBase_C_SetDisplayNewFlag");
static_assert(offsetof(BP_SupportMenuItemDataBase_C_SetDisplayNewFlag, InFlag) == 0x000000, "Member 'BP_SupportMenuItemDataBase_C_SetDisplayNewFlag::InFlag' has a wrong offset!");

// Function BP_SupportMenuItemDataBase.BP_SupportMenuItemDataBase_C.OnChangeNewFlag__DelegateSignature
// 0x0001 (0x0001 - 0x0000)
struct BP_SupportMenuItemDataBase_C_OnChangeNewFlag__DelegateSignature final
{
public:
	bool                                          InIsNew;                                           // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_SupportMenuItemDataBase_C_OnChangeNewFlag__DelegateSignature) == 0x000001, "Wrong alignment on BP_SupportMenuItemDataBase_C_OnChangeNewFlag__DelegateSignature");
static_assert(sizeof(BP_SupportMenuItemDataBase_C_OnChangeNewFlag__DelegateSignature) == 0x000001, "Wrong size on BP_SupportMenuItemDataBase_C_OnChangeNewFlag__DelegateSignature");
static_assert(offsetof(BP_SupportMenuItemDataBase_C_OnChangeNewFlag__DelegateSignature, InIsNew) == 0x000000, "Member 'BP_SupportMenuItemDataBase_C_OnChangeNewFlag__DelegateSignature::InIsNew' has a wrong offset!");

// Function BP_SupportMenuItemDataBase.BP_SupportMenuItemDataBase_C.OnChangeExpansion__DelegateSignature
// 0x0001 (0x0001 - 0x0000)
struct BP_SupportMenuItemDataBase_C_OnChangeExpansion__DelegateSignature final
{
public:
	bool                                          InIsExpansion;                                     // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_SupportMenuItemDataBase_C_OnChangeExpansion__DelegateSignature) == 0x000001, "Wrong alignment on BP_SupportMenuItemDataBase_C_OnChangeExpansion__DelegateSignature");
static_assert(sizeof(BP_SupportMenuItemDataBase_C_OnChangeExpansion__DelegateSignature) == 0x000001, "Wrong size on BP_SupportMenuItemDataBase_C_OnChangeExpansion__DelegateSignature");
static_assert(offsetof(BP_SupportMenuItemDataBase_C_OnChangeExpansion__DelegateSignature, InIsExpansion) == 0x000000, "Member 'BP_SupportMenuItemDataBase_C_OnChangeExpansion__DelegateSignature::InIsExpansion' has a wrong offset!");

// Function BP_SupportMenuItemDataBase.BP_SupportMenuItemDataBase_C.GetTitleText
// 0x0010 (0x0010 - 0x0000)
struct BP_SupportMenuItemDataBase_C_GetTitleText final
{
public:
	class FText                                   OutText;                                           // 0x0000(0x0010)(Parm, OutParm)
};
static_assert(alignof(BP_SupportMenuItemDataBase_C_GetTitleText) == 0x000008, "Wrong alignment on BP_SupportMenuItemDataBase_C_GetTitleText");
static_assert(sizeof(BP_SupportMenuItemDataBase_C_GetTitleText) == 0x000010, "Wrong size on BP_SupportMenuItemDataBase_C_GetTitleText");
static_assert(offsetof(BP_SupportMenuItemDataBase_C_GetTitleText, OutText) == 0x000000, "Member 'BP_SupportMenuItemDataBase_C_GetTitleText::OutText' has a wrong offset!");

// Function BP_SupportMenuItemDataBase.BP_SupportMenuItemDataBase_C.GetTexture
// 0x0028 (0x0028 - 0x0000)
struct BP_SupportMenuItemDataBase_C_GetTexture final
{
public:
	TSoftObjectPtr<class UTexture2D>              OutTexture;                                        // 0x0000(0x0028)(Parm, OutParm, HasGetValueTypeHash)
};
static_assert(alignof(BP_SupportMenuItemDataBase_C_GetTexture) == 0x000008, "Wrong alignment on BP_SupportMenuItemDataBase_C_GetTexture");
static_assert(sizeof(BP_SupportMenuItemDataBase_C_GetTexture) == 0x000028, "Wrong size on BP_SupportMenuItemDataBase_C_GetTexture");
static_assert(offsetof(BP_SupportMenuItemDataBase_C_GetTexture, OutTexture) == 0x000000, "Member 'BP_SupportMenuItemDataBase_C_GetTexture::OutTexture' has a wrong offset!");

// Function BP_SupportMenuItemDataBase.BP_SupportMenuItemDataBase_C.GetItemKeyName
// 0x0008 (0x0008 - 0x0000)
struct BP_SupportMenuItemDataBase_C_GetItemKeyName final
{
public:
	class FName                                   OutKeyName;                                        // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_SupportMenuItemDataBase_C_GetItemKeyName) == 0x000004, "Wrong alignment on BP_SupportMenuItemDataBase_C_GetItemKeyName");
static_assert(sizeof(BP_SupportMenuItemDataBase_C_GetItemKeyName) == 0x000008, "Wrong size on BP_SupportMenuItemDataBase_C_GetItemKeyName");
static_assert(offsetof(BP_SupportMenuItemDataBase_C_GetItemKeyName, OutKeyName) == 0x000000, "Member 'BP_SupportMenuItemDataBase_C_GetItemKeyName::OutKeyName' has a wrong offset!");

// Function BP_SupportMenuItemDataBase.BP_SupportMenuItemDataBase_C.GetIsQuestDeactivate
// 0x0001 (0x0001 - 0x0000)
struct BP_SupportMenuItemDataBase_C_GetIsQuestDeactivate final
{
public:
	bool                                          bOutIsQuestDisable;                                // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_SupportMenuItemDataBase_C_GetIsQuestDeactivate) == 0x000001, "Wrong alignment on BP_SupportMenuItemDataBase_C_GetIsQuestDeactivate");
static_assert(sizeof(BP_SupportMenuItemDataBase_C_GetIsQuestDeactivate) == 0x000001, "Wrong size on BP_SupportMenuItemDataBase_C_GetIsQuestDeactivate");
static_assert(offsetof(BP_SupportMenuItemDataBase_C_GetIsQuestDeactivate, bOutIsQuestDisable) == 0x000000, "Member 'BP_SupportMenuItemDataBase_C_GetIsQuestDeactivate::bOutIsQuestDisable' has a wrong offset!");

// Function BP_SupportMenuItemDataBase.BP_SupportMenuItemDataBase_C.GetIsQuestClear
// 0x0001 (0x0001 - 0x0000)
struct BP_SupportMenuItemDataBase_C_GetIsQuestClear final
{
public:
	bool                                          IsEnable;                                          // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_SupportMenuItemDataBase_C_GetIsQuestClear) == 0x000001, "Wrong alignment on BP_SupportMenuItemDataBase_C_GetIsQuestClear");
static_assert(sizeof(BP_SupportMenuItemDataBase_C_GetIsQuestClear) == 0x000001, "Wrong size on BP_SupportMenuItemDataBase_C_GetIsQuestClear");
static_assert(offsetof(BP_SupportMenuItemDataBase_C_GetIsQuestClear, IsEnable) == 0x000000, "Member 'BP_SupportMenuItemDataBase_C_GetIsQuestClear::IsEnable' has a wrong offset!");

// Function BP_SupportMenuItemDataBase.BP_SupportMenuItemDataBase_C.GetIsFeatureReleased
// 0x0001 (0x0001 - 0x0000)
struct BP_SupportMenuItemDataBase_C_GetIsFeatureReleased final
{
public:
	bool                                          OutIsFeatureReleased;                              // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_SupportMenuItemDataBase_C_GetIsFeatureReleased) == 0x000001, "Wrong alignment on BP_SupportMenuItemDataBase_C_GetIsFeatureReleased");
static_assert(sizeof(BP_SupportMenuItemDataBase_C_GetIsFeatureReleased) == 0x000001, "Wrong size on BP_SupportMenuItemDataBase_C_GetIsFeatureReleased");
static_assert(offsetof(BP_SupportMenuItemDataBase_C_GetIsFeatureReleased, OutIsFeatureReleased) == 0x000000, "Member 'BP_SupportMenuItemDataBase_C_GetIsFeatureReleased::OutIsFeatureReleased' has a wrong offset!");

// Function BP_SupportMenuItemDataBase.BP_SupportMenuItemDataBase_C.GetIsFeatureIconVisibility
// 0x0001 (0x0001 - 0x0000)
struct BP_SupportMenuItemDataBase_C_GetIsFeatureIconVisibility final
{
public:
	bool                                          OutVisibility;                                     // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_SupportMenuItemDataBase_C_GetIsFeatureIconVisibility) == 0x000001, "Wrong alignment on BP_SupportMenuItemDataBase_C_GetIsFeatureIconVisibility");
static_assert(sizeof(BP_SupportMenuItemDataBase_C_GetIsFeatureIconVisibility) == 0x000001, "Wrong size on BP_SupportMenuItemDataBase_C_GetIsFeatureIconVisibility");
static_assert(offsetof(BP_SupportMenuItemDataBase_C_GetIsFeatureIconVisibility, OutVisibility) == 0x000000, "Member 'BP_SupportMenuItemDataBase_C_GetIsFeatureIconVisibility::OutVisibility' has a wrong offset!");

// Function BP_SupportMenuItemDataBase.BP_SupportMenuItemDataBase_C.GetIsFeatureIconGrayOut
// 0x0001 (0x0001 - 0x0000)
struct BP_SupportMenuItemDataBase_C_GetIsFeatureIconGrayOut final
{
public:
	bool                                          OutGrayOut;                                        // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_SupportMenuItemDataBase_C_GetIsFeatureIconGrayOut) == 0x000001, "Wrong alignment on BP_SupportMenuItemDataBase_C_GetIsFeatureIconGrayOut");
static_assert(sizeof(BP_SupportMenuItemDataBase_C_GetIsFeatureIconGrayOut) == 0x000001, "Wrong size on BP_SupportMenuItemDataBase_C_GetIsFeatureIconGrayOut");
static_assert(offsetof(BP_SupportMenuItemDataBase_C_GetIsFeatureIconGrayOut, OutGrayOut) == 0x000000, "Member 'BP_SupportMenuItemDataBase_C_GetIsFeatureIconGrayOut::OutGrayOut' has a wrong offset!");

// Function BP_SupportMenuItemDataBase.BP_SupportMenuItemDataBase_C.GetIsExpansion
// 0x0001 (0x0001 - 0x0000)
struct BP_SupportMenuItemDataBase_C_GetIsExpansion final
{
public:
	bool                                          OutFlag;                                           // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_SupportMenuItemDataBase_C_GetIsExpansion) == 0x000001, "Wrong alignment on BP_SupportMenuItemDataBase_C_GetIsExpansion");
static_assert(sizeof(BP_SupportMenuItemDataBase_C_GetIsExpansion) == 0x000001, "Wrong size on BP_SupportMenuItemDataBase_C_GetIsExpansion");
static_assert(offsetof(BP_SupportMenuItemDataBase_C_GetIsExpansion, OutFlag) == 0x000000, "Member 'BP_SupportMenuItemDataBase_C_GetIsExpansion::OutFlag' has a wrong offset!");

// Function BP_SupportMenuItemDataBase.BP_SupportMenuItemDataBase_C.GetIsCategory
// 0x0001 (0x0001 - 0x0000)
struct BP_SupportMenuItemDataBase_C_GetIsCategory final
{
public:
	bool                                          OutIsCategory;                                     // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_SupportMenuItemDataBase_C_GetIsCategory) == 0x000001, "Wrong alignment on BP_SupportMenuItemDataBase_C_GetIsCategory");
static_assert(sizeof(BP_SupportMenuItemDataBase_C_GetIsCategory) == 0x000001, "Wrong size on BP_SupportMenuItemDataBase_C_GetIsCategory");
static_assert(offsetof(BP_SupportMenuItemDataBase_C_GetIsCategory, OutIsCategory) == 0x000000, "Member 'BP_SupportMenuItemDataBase_C_GetIsCategory::OutIsCategory' has a wrong offset!");

// Function BP_SupportMenuItemDataBase.BP_SupportMenuItemDataBase_C.GetDisplayNewFlag
// 0x0001 (0x0001 - 0x0000)
struct BP_SupportMenuItemDataBase_C_GetDisplayNewFlag final
{
public:
	bool                                          OutFlag;                                           // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_SupportMenuItemDataBase_C_GetDisplayNewFlag) == 0x000001, "Wrong alignment on BP_SupportMenuItemDataBase_C_GetDisplayNewFlag");
static_assert(sizeof(BP_SupportMenuItemDataBase_C_GetDisplayNewFlag) == 0x000001, "Wrong size on BP_SupportMenuItemDataBase_C_GetDisplayNewFlag");
static_assert(offsetof(BP_SupportMenuItemDataBase_C_GetDisplayNewFlag, OutFlag) == 0x000000, "Member 'BP_SupportMenuItemDataBase_C_GetDisplayNewFlag::OutFlag' has a wrong offset!");

// Function BP_SupportMenuItemDataBase.BP_SupportMenuItemDataBase_C.GetDescriptionTextFinished
// 0x0010 (0x0010 - 0x0000)
struct BP_SupportMenuItemDataBase_C_GetDescriptionTextFinished final
{
public:
	class FText                                   OutText;                                           // 0x0000(0x0010)(Parm, OutParm)
};
static_assert(alignof(BP_SupportMenuItemDataBase_C_GetDescriptionTextFinished) == 0x000008, "Wrong alignment on BP_SupportMenuItemDataBase_C_GetDescriptionTextFinished");
static_assert(sizeof(BP_SupportMenuItemDataBase_C_GetDescriptionTextFinished) == 0x000010, "Wrong size on BP_SupportMenuItemDataBase_C_GetDescriptionTextFinished");
static_assert(offsetof(BP_SupportMenuItemDataBase_C_GetDescriptionTextFinished, OutText) == 0x000000, "Member 'BP_SupportMenuItemDataBase_C_GetDescriptionTextFinished::OutText' has a wrong offset!");

// Function BP_SupportMenuItemDataBase.BP_SupportMenuItemDataBase_C.GetDescriptionText
// 0x0010 (0x0010 - 0x0000)
struct BP_SupportMenuItemDataBase_C_GetDescriptionText final
{
public:
	class FText                                   OutText;                                           // 0x0000(0x0010)(Parm, OutParm)
};
static_assert(alignof(BP_SupportMenuItemDataBase_C_GetDescriptionText) == 0x000008, "Wrong alignment on BP_SupportMenuItemDataBase_C_GetDescriptionText");
static_assert(sizeof(BP_SupportMenuItemDataBase_C_GetDescriptionText) == 0x000010, "Wrong size on BP_SupportMenuItemDataBase_C_GetDescriptionText");
static_assert(offsetof(BP_SupportMenuItemDataBase_C_GetDescriptionText, OutText) == 0x000000, "Member 'BP_SupportMenuItemDataBase_C_GetDescriptionText::OutText' has a wrong offset!");

// Function BP_SupportMenuItemDataBase.BP_SupportMenuItemDataBase_C.GetCategoryKeyList
// 0x0010 (0x0010 - 0x0000)
struct BP_SupportMenuItemDataBase_C_GetCategoryKeyList final
{
public:
	TArray<class FName>                           OutCategoryList;                                   // 0x0000(0x0010)(Parm, OutParm)
};
static_assert(alignof(BP_SupportMenuItemDataBase_C_GetCategoryKeyList) == 0x000008, "Wrong alignment on BP_SupportMenuItemDataBase_C_GetCategoryKeyList");
static_assert(sizeof(BP_SupportMenuItemDataBase_C_GetCategoryKeyList) == 0x000010, "Wrong size on BP_SupportMenuItemDataBase_C_GetCategoryKeyList");
static_assert(offsetof(BP_SupportMenuItemDataBase_C_GetCategoryKeyList, OutCategoryList) == 0x000000, "Member 'BP_SupportMenuItemDataBase_C_GetCategoryKeyList::OutCategoryList' has a wrong offset!");

}

