#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SaveDataSelectItem

#include "Basic.hpp"

#include "BasicUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_SaveDataSelectItem.BP_SaveDataSelectItem_C
// 0x0000 (0x0030 - 0x0030)
class UBP_SaveDataSelectItem_C final : public UScrollerItem
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_SaveDataSelectItem_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_SaveDataSelectItem_C")
	}
	static class UBP_SaveDataSelectItem_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_SaveDataSelectItem_C>();
	}
};
DUMPER7_ASSERTS_UBP_SaveDataSelectItem_C;

}

