#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TitleMenuUIObject

#include "Basic.hpp"

#include "BP_TitleMenuUIObject_classes.hpp"
#include "BP_TitleMenuUIObject_parameters.hpp"


namespace SDK
{

// Function BP_TitleMenuUIObject.BP_TitleMenuUIObject_C.Clear
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_TitleMenuUIObject_C::Clear()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TitleMenuUIObject_C", "Clear");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_TitleMenuUIObject.BP_TitleMenuUIObject_C.ContinueLastGame
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_TitleMenuUIObject_C::ContinueLastGame()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TitleMenuUIObject_C", "ContinueLastGame");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_TitleMenuUIObject.BP_TitleMenuUIObject_C.ExecuteUbergraph_BP_TitleMenuUIObject
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_TitleMenuUIObject_C::ExecuteUbergraph_BP_TitleMenuUIObject(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TitleMenuUIObject_C", "ExecuteUbergraph_BP_TitleMenuUIObject");

	Params::BP_TitleMenuUIObject_C_ExecuteUbergraph_BP_TitleMenuUIObject Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_TitleMenuUIObject.BP_TitleMenuUIObject_C.GetContinueSaveName
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FString*                          SaveName                                               (Parm, OutParm, ZeroConstructor, HasGetValueTypeHash)

void UBP_TitleMenuUIObject_C::GetContinueSaveName(class FString* SaveName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TitleMenuUIObject_C", "GetContinueSaveName");

	Params::BP_TitleMenuUIObject_C_GetContinueSaveName Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (SaveName != nullptr)
		*SaveName = std::move(Parms.SaveName);
}


// Function BP_TitleMenuUIObject.BP_TitleMenuUIObject_C.IsAbleToContinue
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool*                                   EnableContinue                                         (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_TitleMenuUIObject_C::IsAbleToContinue(bool* EnableContinue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TitleMenuUIObject_C", "IsAbleToContinue");

	Params::BP_TitleMenuUIObject_C_IsAbleToContinue Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (EnableContinue != nullptr)
		*EnableContinue = Parms.EnableContinue;
}


// Function BP_TitleMenuUIObject.BP_TitleMenuUIObject_C.OnChangeTestCharacterView
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bIsInEnable                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_TitleMenuUIObject_C::OnChangeTestCharacterView(bool bIsInEnable)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TitleMenuUIObject_C", "OnChangeTestCharacterView");

	Params::BP_TitleMenuUIObject_C_OnChangeTestCharacterView Parms{};

	Parms.bIsInEnable = bIsInEnable;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_TitleMenuUIObject.BP_TitleMenuUIObject_C.OnChangeTitleProgress
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// ETitleProgressType                      Progress                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_TitleMenuUIObject_C::OnChangeTitleProgress(ETitleProgressType Progress)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TitleMenuUIObject_C", "OnChangeTitleProgress");

	Params::BP_TitleMenuUIObject_C_OnChangeTitleProgress Parms{};

	Parms.Progress = Progress;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_TitleMenuUIObject.BP_TitleMenuUIObject_C.OnOtherMenuClosed
// (BlueprintCallable, BlueprintEvent)

void UBP_TitleMenuUIObject_C::OnOtherMenuClosed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TitleMenuUIObject_C", "OnOtherMenuClosed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_TitleMenuUIObject.BP_TitleMenuUIObject_C.OnSaveDataSelect
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   InIndex                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_TitleMenuUIObject_C::OnSaveDataSelect(int32 InIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TitleMenuUIObject_C", "OnSaveDataSelect");

	Params::BP_TitleMenuUIObject_C_OnSaveDataSelect Parms{};

	Parms.InIndex = InIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_TitleMenuUIObject.BP_TitleMenuUIObject_C.OnTitleMenuClosed
// (BlueprintCallable, BlueprintEvent)

void UBP_TitleMenuUIObject_C::OnTitleMenuClosed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TitleMenuUIObject_C", "OnTitleMenuClosed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_TitleMenuUIObject.BP_TitleMenuUIObject_C.Open
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool UBP_TitleMenuUIObject_C::Open()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TitleMenuUIObject_C", "Open");

	Params::BP_TitleMenuUIObject_C_Open Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_TitleMenuUIObject.BP_TitleMenuUIObject_C.OpenConfig
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UBP_TitleMenuUIObject_C::OpenConfig()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TitleMenuUIObject_C", "OpenConfig");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_TitleMenuUIObject.BP_TitleMenuUIObject_C.OpenLicense
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UBP_TitleMenuUIObject_C::OpenLicense()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TitleMenuUIObject_C", "OpenLicense");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_TitleMenuUIObject.BP_TitleMenuUIObject_C.OpenSaveDataSelectMenu
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// EUISaveDataGroup                        InSaveDataGroup                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_TitleMenuUIObject_C::OpenSaveDataSelectMenu(EUISaveDataGroup InSaveDataGroup)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TitleMenuUIObject_C", "OpenSaveDataSelectMenu");

	Params::BP_TitleMenuUIObject_C_OpenSaveDataSelectMenu Parms{};

	Parms.InSaveDataGroup = InSaveDataGroup;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_TitleMenuUIObject.BP_TitleMenuUIObject_C.RequestPlayBGM
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const ETitleProgressType&               InProgress                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    ForcePlay                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_TitleMenuUIObject_C::RequestPlayBGM(const ETitleProgressType& InProgress, bool ForcePlay)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TitleMenuUIObject_C", "RequestPlayBGM");

	Params::BP_TitleMenuUIObject_C_RequestPlayBGM Parms{};

	Parms.InProgress = InProgress;
	Parms.ForcePlay = ForcePlay;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_TitleMenuUIObject.BP_TitleMenuUIObject_C.RequestStopBGM
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// ETitleProgressType                      Progress                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_TitleMenuUIObject_C::RequestStopBGM(ETitleProgressType Progress)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TitleMenuUIObject_C", "RequestStopBGM");

	Params::BP_TitleMenuUIObject_C_RequestStopBGM Parms{};

	Parms.Progress = Progress;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_TitleMenuUIObject.BP_TitleMenuUIObject_C.SetGameStartFromOther
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_TitleMenuUIObject_C::SetGameStartFromOther()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TitleMenuUIObject_C", "SetGameStartFromOther");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_TitleMenuUIObject.BP_TitleMenuUIObject_C.SetNewGameStoryFlag
// (BlueprintCallable, BlueprintEvent)

void UBP_TitleMenuUIObject_C::SetNewGameStoryFlag()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TitleMenuUIObject_C", "SetNewGameStoryFlag");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_TitleMenuUIObject.BP_TitleMenuUIObject_C.StartNewGame
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsFemale                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_TitleMenuUIObject_C::StartNewGame(bool IsFemale)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TitleMenuUIObject_C", "StartNewGame");

	Params::BP_TitleMenuUIObject_C_StartNewGame Parms{};

	Parms.IsFemale = IsFemale;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_TitleMenuUIObject.BP_TitleMenuUIObject_C.TransitToMainWorld
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_TitleMenuUIObject_C::TransitToMainWorld()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TitleMenuUIObject_C", "TransitToMainWorld");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_TitleMenuUIObject.BP_TitleMenuUIObject_C.TransitToOtherMenu
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_TitleMenuUIObject_C::TransitToOtherMenu()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TitleMenuUIObject_C", "TransitToOtherMenu");

	UObject::ProcessEvent(Func, nullptr);
}

}

