#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_PC_Interface

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPI_PC_Interface.BPI_PC_Interface_C
// 0x0000 (0x0028 - 0x0028)
class IBPI_PC_Interface_C final : public IInterface
{
public:
	class UAnimInstance* Get_PC_ABP_Cinematics_HumanBone();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BPI_PC_Interface_C">();
	}
	static class IBPI_PC_Interface_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IBPI_PC_Interface_C>();
	}
};
static_assert(alignof(IBPI_PC_Interface_C) == 0x000008, "Wrong alignment on IBPI_PC_Interface_C");
static_assert(sizeof(IBPI_PC_Interface_C) == 0x000028, "Wrong size on IBPI_PC_Interface_C");

}

