#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CR_BF_GiantNBone_AuxBone

#include "Basic.hpp"

#include "ControlRig_classes.hpp"


namespace SDK
{

// ControlRigBlueprintGeneratedClass CR_BF_GiantNBone_AuxBone.CR_BF_GiantNBone_AuxBone_C
// 0x0000 (0x0B20 - 0x0B20)
class UCR_BF_GiantNBone_AuxBone_C final : public UControlRig
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("CR_BF_GiantNBone_AuxBone_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CR_BF_GiantNBone_AuxBone_C")
	}
	static class UCR_BF_GiantNBone_AuxBone_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCR_BF_GiantNBone_AuxBone_C>();
	}
};
DUMPER7_ASSERTS_UCR_BF_GiantNBone_AuxBone_C;

}

