#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_ReactToActivationFailureDueToDisable_OnAir

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Extensions_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_ReactToActivationFailureDueToDisable_OnAir.GA_ReactToActivationFailureDueToDisable_OnAir_C
// 0x0008 (0x0548 - 0x0540)
class UGA_ReactToActivationFailureDueToDisable_OnAir_C final : public UActionHumanGameplayAbility
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0540(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_GA_ReactToActivationFailureDueToDisable_OnAir(int32 EntryPoint);
	void K2_ActivateAbility();
	void OnBlendOut_A7011AC9405C1D925FAF60B4D7557BF6();
	void OnCancelled_A7011AC9405C1D925FAF60B4D7557BF6();
	void OnCompleted_A7011AC9405C1D925FAF60B4D7557BF6();
	void OnInterrupted_A7011AC9405C1D925FAF60B4D7557BF6();
	void OnMontageNotifyBegin_A7011AC9405C1D925FAF60B4D7557BF6(const class FName InName, const struct FAnimNotifyEvent& InNotifyEvent);
	void OnMontageNotifyEnd_A7011AC9405C1D925FAF60B4D7557BF6(const class FName InName, const struct FAnimNotifyEvent& InNotifyEvent);
	void OnTaskDestroyed_A7011AC9405C1D925FAF60B4D7557BF6();
	void OnTotalDurationExpiredOrTaskDestroyed_A7011AC9405C1D925FAF60B4D7557BF6();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GA_ReactToActivationFailureDueToDisable_OnAir_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GA_ReactToActivationFailureDueToDisable_OnAir_C")
	}
	static class UGA_ReactToActivationFailureDueToDisable_OnAir_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_ReactToActivationFailureDueToDisable_OnAir_C>();
	}
};
DUMPER7_ASSERTS_UGA_ReactToActivationFailureDueToDisable_OnAir_C;

}

