#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GCN_StatusEffect_Looping_Essential

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Extensions_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GCN_StatusEffect_Looping_Essential.GCN_StatusEffect_Looping_Essential_C
// 0x0008 (0x0F08 - 0x0F00)
class AGCN_StatusEffect_Looping_Essential_C : public AGCN_StatusEffect_Looping
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0F00(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_GCN_StatusEffect_Looping_Essential(int32 EntryPoint);
	void OnApplication(class AActor* Target, const struct FGameplayCueParameters& Parameters, const struct FGameplayCueNotify_SpawnResult& SpawnResults);
	void OnRecurring(class AActor* Target, const struct FGameplayCueParameters& Parameters, const struct FGameplayCueNotify_SpawnResult& SpawnResults);
	void OnRemoval(class AActor* Target, const struct FGameplayCueParameters& Parameters, const struct FGameplayCueNotify_SpawnResult& SpawnResults);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GCN_StatusEffect_Looping_Essential_C">();
	}
	static class AGCN_StatusEffect_Looping_Essential_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGCN_StatusEffect_Looping_Essential_C>();
	}
};
static_assert(alignof(AGCN_StatusEffect_Looping_Essential_C) == 0x000008, "Wrong alignment on AGCN_StatusEffect_Looping_Essential_C");
static_assert(sizeof(AGCN_StatusEffect_Looping_Essential_C) == 0x000F08, "Wrong size on AGCN_StatusEffect_Looping_Essential_C");
static_assert(offsetof(AGCN_StatusEffect_Looping_Essential_C, UberGraphFrame) == 0x000F00, "Member 'AGCN_StatusEffect_Looping_Essential_C::UberGraphFrame' has a wrong offset!");

}

