#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GPC_Gatling_SE

#include "Basic.hpp"

#include "GPC_SE_RTPC_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GPC_Gatling_SE.GPC_Gatling_SE_C
// 0x0000 (0x0F20 - 0x0F20)
class AGPC_Gatling_SE_C final : public AGPC_SE_RTPC_C
{
public:
	void InitializeEffect(const struct FGameplayCueParameters& Parameters);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GPC_Gatling_SE_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GPC_Gatling_SE_C")
	}
	static class AGPC_Gatling_SE_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGPC_Gatling_SE_C>();
	}
};
DUMPER7_ASSERTS_AGPC_Gatling_SE_C;

}

