#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SQ_SummonBuddy

#include "Basic.hpp"

#include "SQ_SummonBuddy_classes.hpp"
#include "SQ_SummonBuddy_parameters.hpp"


namespace SDK
{

// Function SQ_SummonBuddy.SQ_SummonBuddy_DirectorBP_C.ExecuteUbergraph_SQ_SummonBuddy_DirectorBP
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USQ_SummonBuddy_DirectorBP_C::ExecuteUbergraph_SQ_SummonBuddy_DirectorBP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SQ_SummonBuddy_DirectorBP_C", "ExecuteUbergraph_SQ_SummonBuddy_DirectorBP");

	Params::SQ_SummonBuddy_DirectorBP_C_ExecuteUbergraph_SQ_SummonBuddy_DirectorBP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SQ_SummonBuddy.SQ_SummonBuddy_DirectorBP_C.GetBindingBuddy
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ACharacter**                      AsCharacter                                            (Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void USQ_SummonBuddy_DirectorBP_C::GetBindingBuddy(class ACharacter** AsCharacter)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SQ_SummonBuddy_DirectorBP_C", "GetBindingBuddy");

	Params::SQ_SummonBuddy_DirectorBP_C_GetBindingBuddy Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AsCharacter != nullptr)
		*AsCharacter = Parms.AsCharacter;
}


// Function SQ_SummonBuddy.SQ_SummonBuddy_DirectorBP_C.GetBindingPlayer
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ACharacter**                      AsCharacter                                            (Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void USQ_SummonBuddy_DirectorBP_C::GetBindingPlayer(class ACharacter** AsCharacter)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SQ_SummonBuddy_DirectorBP_C", "GetBindingPlayer");

	Params::SQ_SummonBuddy_DirectorBP_C_GetBindingPlayer Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AsCharacter != nullptr)
		*AsCharacter = Parms.AsCharacter;
}


// Function SQ_SummonBuddy.SQ_SummonBuddy_DirectorBP_C.GetNPCTransform
// (BlueprintCallable, BlueprintEvent)

void USQ_SummonBuddy_DirectorBP_C::GetNPCTransform()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SQ_SummonBuddy_DirectorBP_C", "GetNPCTransform");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SQ_SummonBuddy.SQ_SummonBuddy_DirectorBP_C.GetPlayerTransform
// (BlueprintCallable, BlueprintEvent)

void USQ_SummonBuddy_DirectorBP_C::GetPlayerTransform()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SQ_SummonBuddy_DirectorBP_C", "GetPlayerTransform");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SQ_SummonBuddy.SQ_SummonBuddy_DirectorBP_C.GetVisualControl
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class AActor*                           Actor                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UBP_PlayerVisualControl_C**       Result                                                 (Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void USQ_SummonBuddy_DirectorBP_C::GetVisualControl(class AActor* Actor, class UBP_PlayerVisualControl_C** Result)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SQ_SummonBuddy_DirectorBP_C", "GetVisualControl");

	Params::SQ_SummonBuddy_DirectorBP_C_GetVisualControl Parms{};

	Parms.Actor = Actor;

	UObject::ProcessEvent(Func, &Parms);

	if (Result != nullptr)
		*Result = Parms.Result;
}


// Function SQ_SummonBuddy.SQ_SummonBuddy_DirectorBP_C.Heart_Tick
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AStaticMeshActor*                 Heart                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void USQ_SummonBuddy_DirectorBP_C::Heart_Tick(class AStaticMeshActor* Heart)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SQ_SummonBuddy_DirectorBP_C", "Heart_Tick");

	Params::SQ_SummonBuddy_DirectorBP_C_Heart_Tick Parms{};

	Parms.Heart = Heart;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SQ_SummonBuddy.SQ_SummonBuddy_DirectorBP_C.NS_Summon_Buddy_Appear_Line_Event
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ANiagaraActor*                    NS_Summon_Buddy_Appear_Line_0                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void USQ_SummonBuddy_DirectorBP_C::NS_Summon_Buddy_Appear_Line_Event(class ANiagaraActor* NS_Summon_Buddy_Appear_Line_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SQ_SummonBuddy_DirectorBP_C", "NS_Summon_Buddy_Appear_Line_Event");

	Params::SQ_SummonBuddy_DirectorBP_C_NS_Summon_Buddy_Appear_Line_Event Parms{};

	Parms.NS_Summon_Buddy_Appear_Line_0 = NS_Summon_Buddy_Appear_Line_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SQ_SummonBuddy.SQ_SummonBuddy_DirectorBP_C.NS_Summon_Buddy_Appear_Line_Event_Tick
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ANiagaraActor*                    NS_Summon_Buddy_Appear_Line_0                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void USQ_SummonBuddy_DirectorBP_C::NS_Summon_Buddy_Appear_Line_Event_Tick(class ANiagaraActor* NS_Summon_Buddy_Appear_Line_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SQ_SummonBuddy_DirectorBP_C", "NS_Summon_Buddy_Appear_Line_Event_Tick");

	Params::SQ_SummonBuddy_DirectorBP_C_NS_Summon_Buddy_Appear_Line_Event_Tick Parms{};

	Parms.NS_Summon_Buddy_Appear_Line_0 = NS_Summon_Buddy_Appear_Line_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SQ_SummonBuddy.SQ_SummonBuddy_DirectorBP_C.NS_Summon_Buddy_Burst_Pt_Event_Begin
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ANiagaraActor*                    NS_Summon_Buddy_Burst_Pt_0                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void USQ_SummonBuddy_DirectorBP_C::NS_Summon_Buddy_Burst_Pt_Event_Begin(class ANiagaraActor* NS_Summon_Buddy_Burst_Pt_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SQ_SummonBuddy_DirectorBP_C", "NS_Summon_Buddy_Burst_Pt_Event_Begin");

	Params::SQ_SummonBuddy_DirectorBP_C_NS_Summon_Buddy_Burst_Pt_Event_Begin Parms{};

	Parms.NS_Summon_Buddy_Burst_Pt_0 = NS_Summon_Buddy_Burst_Pt_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SQ_SummonBuddy.SQ_SummonBuddy_DirectorBP_C.NS_Summon_Buddy_Glow_Ball_Event
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ANiagaraActor*                    NS_Summon_Buddy_Glow_Ball_0                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void USQ_SummonBuddy_DirectorBP_C::NS_Summon_Buddy_Glow_Ball_Event(class ANiagaraActor* NS_Summon_Buddy_Glow_Ball_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SQ_SummonBuddy_DirectorBP_C", "NS_Summon_Buddy_Glow_Ball_Event");

	Params::SQ_SummonBuddy_DirectorBP_C_NS_Summon_Buddy_Glow_Ball_Event Parms{};

	Parms.NS_Summon_Buddy_Glow_Ball_0 = NS_Summon_Buddy_Glow_Ball_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SQ_SummonBuddy.SQ_SummonBuddy_DirectorBP_C.NS_Summon_Buddy_SetParameter
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ANiagaraActor*                    NS_Summon_Buddy_Begin                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void USQ_SummonBuddy_DirectorBP_C::NS_Summon_Buddy_SetParameter(class ANiagaraActor* NS_Summon_Buddy_Begin)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SQ_SummonBuddy_DirectorBP_C", "NS_Summon_Buddy_SetParameter");

	Params::SQ_SummonBuddy_DirectorBP_C_NS_Summon_Buddy_SetParameter Parms{};

	Parms.NS_Summon_Buddy_Begin = NS_Summon_Buddy_Begin;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SQ_SummonBuddy.SQ_SummonBuddy_DirectorBP_C.SequenceEvent__ENTRYPOINTSQ_SummonBuddy_DirectorBP
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ANiagaraActor*                    NS_Summon_Buddy_Begin                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void USQ_SummonBuddy_DirectorBP_C::SequenceEvent__ENTRYPOINTSQ_SummonBuddy_DirectorBP(class ANiagaraActor* NS_Summon_Buddy_Begin)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SQ_SummonBuddy_DirectorBP_C", "SequenceEvent__ENTRYPOINTSQ_SummonBuddy_DirectorBP");

	Params::SQ_SummonBuddy_DirectorBP_C_SequenceEvent__ENTRYPOINTSQ_SummonBuddy_DirectorBP Parms{};

	Parms.NS_Summon_Buddy_Begin = NS_Summon_Buddy_Begin;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SQ_SummonBuddy.SQ_SummonBuddy_DirectorBP_C.SequenceEvent__ENTRYPOINTSQ_SummonBuddy_DirectorBP_0
// (Public, BlueprintCallable, BlueprintEvent)

void USQ_SummonBuddy_DirectorBP_C::SequenceEvent__ENTRYPOINTSQ_SummonBuddy_DirectorBP_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SQ_SummonBuddy_DirectorBP_C", "SequenceEvent__ENTRYPOINTSQ_SummonBuddy_DirectorBP_0");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SQ_SummonBuddy.SQ_SummonBuddy_DirectorBP_C.SequenceEvent__ENTRYPOINTSQ_SummonBuddy_DirectorBP_1
// (Public, BlueprintCallable, BlueprintEvent)

void USQ_SummonBuddy_DirectorBP_C::SequenceEvent__ENTRYPOINTSQ_SummonBuddy_DirectorBP_1()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SQ_SummonBuddy_DirectorBP_C", "SequenceEvent__ENTRYPOINTSQ_SummonBuddy_DirectorBP_1");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SQ_SummonBuddy.SQ_SummonBuddy_DirectorBP_C.SequenceEvent__ENTRYPOINTSQ_SummonBuddy_DirectorBP_2
// (Public, BlueprintCallable, BlueprintEvent)

void USQ_SummonBuddy_DirectorBP_C::SequenceEvent__ENTRYPOINTSQ_SummonBuddy_DirectorBP_2()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SQ_SummonBuddy_DirectorBP_C", "SequenceEvent__ENTRYPOINTSQ_SummonBuddy_DirectorBP_2");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SQ_SummonBuddy.SQ_SummonBuddy_DirectorBP_C.SequenceEvent__ENTRYPOINTSQ_SummonBuddy_DirectorBP_3
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ANiagaraActor*                    NS_Summon_Buddy_Burst_Pt_0                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void USQ_SummonBuddy_DirectorBP_C::SequenceEvent__ENTRYPOINTSQ_SummonBuddy_DirectorBP_3(class ANiagaraActor* NS_Summon_Buddy_Burst_Pt_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SQ_SummonBuddy_DirectorBP_C", "SequenceEvent__ENTRYPOINTSQ_SummonBuddy_DirectorBP_3");

	Params::SQ_SummonBuddy_DirectorBP_C_SequenceEvent__ENTRYPOINTSQ_SummonBuddy_DirectorBP_3 Parms{};

	Parms.NS_Summon_Buddy_Burst_Pt_0 = NS_Summon_Buddy_Burst_Pt_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SQ_SummonBuddy.SQ_SummonBuddy_DirectorBP_C.SequenceEvent__ENTRYPOINTSQ_SummonBuddy_DirectorBP_4
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ANiagaraActor*                    NS_Summon_Buddy_Glow_Ball_0                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void USQ_SummonBuddy_DirectorBP_C::SequenceEvent__ENTRYPOINTSQ_SummonBuddy_DirectorBP_4(class ANiagaraActor* NS_Summon_Buddy_Glow_Ball_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SQ_SummonBuddy_DirectorBP_C", "SequenceEvent__ENTRYPOINTSQ_SummonBuddy_DirectorBP_4");

	Params::SQ_SummonBuddy_DirectorBP_C_SequenceEvent__ENTRYPOINTSQ_SummonBuddy_DirectorBP_4 Parms{};

	Parms.NS_Summon_Buddy_Glow_Ball_0 = NS_Summon_Buddy_Glow_Ball_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SQ_SummonBuddy.SQ_SummonBuddy_DirectorBP_C.SequenceEvent__ENTRYPOINTSQ_SummonBuddy_DirectorBP_5
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ANiagaraActor*                    NS_Summon_Buddy_Appear_Line_0                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void USQ_SummonBuddy_DirectorBP_C::SequenceEvent__ENTRYPOINTSQ_SummonBuddy_DirectorBP_5(class ANiagaraActor* NS_Summon_Buddy_Appear_Line_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SQ_SummonBuddy_DirectorBP_C", "SequenceEvent__ENTRYPOINTSQ_SummonBuddy_DirectorBP_5");

	Params::SQ_SummonBuddy_DirectorBP_C_SequenceEvent__ENTRYPOINTSQ_SummonBuddy_DirectorBP_5 Parms{};

	Parms.NS_Summon_Buddy_Appear_Line_0 = NS_Summon_Buddy_Appear_Line_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SQ_SummonBuddy.SQ_SummonBuddy_DirectorBP_C.SequenceEvent__ENTRYPOINTSQ_SummonBuddy_DirectorBP_6
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ANiagaraActor*                    NS_Summon_Buddy_Appear_Line_0                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void USQ_SummonBuddy_DirectorBP_C::SequenceEvent__ENTRYPOINTSQ_SummonBuddy_DirectorBP_6(class ANiagaraActor* NS_Summon_Buddy_Appear_Line_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SQ_SummonBuddy_DirectorBP_C", "SequenceEvent__ENTRYPOINTSQ_SummonBuddy_DirectorBP_6");

	Params::SQ_SummonBuddy_DirectorBP_C_SequenceEvent__ENTRYPOINTSQ_SummonBuddy_DirectorBP_6 Parms{};

	Parms.NS_Summon_Buddy_Appear_Line_0 = NS_Summon_Buddy_Appear_Line_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SQ_SummonBuddy.SQ_SummonBuddy_DirectorBP_C.SequenceEvent__ENTRYPOINTSQ_SummonBuddy_DirectorBP_7
// (Public, BlueprintCallable, BlueprintEvent)

void USQ_SummonBuddy_DirectorBP_C::SequenceEvent__ENTRYPOINTSQ_SummonBuddy_DirectorBP_7()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SQ_SummonBuddy_DirectorBP_C", "SequenceEvent__ENTRYPOINTSQ_SummonBuddy_DirectorBP_7");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SQ_SummonBuddy.SQ_SummonBuddy_DirectorBP_C.SetMaterialParameter_VanishCenter
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UMeshComponent*                   Mesh                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// class FName                             Parameter                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USQ_SummonBuddy_DirectorBP_C::SetMaterialParameter_VanishCenter(class UMeshComponent* Mesh, class FName Parameter)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SQ_SummonBuddy_DirectorBP_C", "SetMaterialParameter_VanishCenter");

	Params::SQ_SummonBuddy_DirectorBP_C_SetMaterialParameter_VanishCenter Parms{};

	Parms.Mesh = Mesh;
	Parms.Parameter = Parameter;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SQ_SummonBuddy.SQ_SummonBuddy_DirectorBP_C.ShowBuddy
// (BlueprintCallable, BlueprintEvent)

void USQ_SummonBuddy_DirectorBP_C::ShowBuddy()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SQ_SummonBuddy_DirectorBP_C", "ShowBuddy");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SQ_SummonBuddy.SQ_SummonBuddy_DirectorBP_C.ShowBuddy_Begin
// (BlueprintCallable, BlueprintEvent)

void USQ_SummonBuddy_DirectorBP_C::ShowBuddy_Begin()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SQ_SummonBuddy_DirectorBP_C", "ShowBuddy_Begin");

	UObject::ProcessEvent(Func, nullptr);
}

}

