#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: STR_GainItemSmallScenario

#include "Basic.hpp"

#include "StoryFlagSystem_structs.hpp"
#include "Extensions_structs.hpp"


namespace SDK
{

// UserDefinedStruct STR_GainItemSmallScenario.STR_GainItemSmallScenario
// 0x0050 (0x0050 - 0x0000)
struct FSTR_GainItemSmallScenario final
{
public:
	struct FStoryFlagEvaluationFormula            EvaluationFormula_3_0F17F5BF44BCD34818F19BB6E814672A; // 0x0000(0x0010)(Edit, BlueprintVisible, HasGetValueTypeHash)
	struct FArticleAddInfo_BloodCode              BloodCode_14_A6A9930545C5B883E992F9B733CFCE08;     // 0x0010(0x0030)(Edit, BlueprintVisible)
	struct FArticleBulkInfo                       Booster_7_52E5F2D0402879686971C5AC8630B712;        // 0x0040(0x0010)(Edit, BlueprintVisible)
};
static_assert(alignof(FSTR_GainItemSmallScenario) == 0x000008, "Wrong alignment on FSTR_GainItemSmallScenario");
static_assert(sizeof(FSTR_GainItemSmallScenario) == 0x000050, "Wrong size on FSTR_GainItemSmallScenario");
static_assert(offsetof(FSTR_GainItemSmallScenario, EvaluationFormula_3_0F17F5BF44BCD34818F19BB6E814672A) == 0x000000, "Member 'FSTR_GainItemSmallScenario::EvaluationFormula_3_0F17F5BF44BCD34818F19BB6E814672A' has a wrong offset!");
static_assert(offsetof(FSTR_GainItemSmallScenario, BloodCode_14_A6A9930545C5B883E992F9B733CFCE08) == 0x000010, "Member 'FSTR_GainItemSmallScenario::BloodCode_14_A6A9930545C5B883E992F9B733CFCE08' has a wrong offset!");
static_assert(offsetof(FSTR_GainItemSmallScenario, Booster_7_52E5F2D0402879686971C5AC8630B712) == 0x000040, "Member 'FSTR_GainItemSmallScenario::Booster_7_52E5F2D0402879686971C5AC8630B712' has a wrong offset!");

}

