#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TS_XP

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass TS_XP.TS_XP_C
// 0x0000 (0x01B0 - 0x01B0)
class UTS_XP_C final : public UCommonTextStyle
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("TS_XP_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"TS_XP_C")
	}
	static class UTS_XP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTS_XP_C>();
	}
};
DUMPER7_ASSERTS_UTS_XP_C;

}

