#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WDT_ConfigHeader

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BasicUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WDT_ConfigHeader.WDT_ConfigHeader_C
// 0x00E0 (0x06A8 - 0x05C8)
class UWDT_ConfigHeader_C final : public UMenuPieceBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x05C8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWDT_ConfigIconTextPiece_C*             BackIconText;                                      // 0x05D0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       ConfigTitle;                                       // 0x05D8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       ConfigTitle_Shadow;                                // 0x05E0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWDT_ConfigIconTextPiece_C*             InitializeIconText;                                // 0x05E8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWDT_ConfigIconTextPiece_C*             LanguageIconText;                                  // 0x05F0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpacer*                                Spacer;                                            // 0x05F8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpacer*                                Spacer_45;                                         // 0x0600(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOverlay*                               TitleOverlay;                                      // 0x0608(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVerticalBox*                           VerticalBox_Tab;                                   // 0x0610(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWDT_ConfigTab_C*                       WDT_ConfigTab;                                     // 0x0618(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class FText                                   BackText;                                          // 0x0620(0x0010)(Edit, BlueprintVisible)
	class FText                                   TitleText;                                         // 0x0630(0x0010)(Edit, BlueprintVisible)
	bool                                          bIsTopMenu;                                        // 0x0640(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bUseTab;                                           // 0x0641(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_642[0x6];                                      // 0x0642(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class FText>                           TabTextList;                                       // 0x0648(0x0010)(Edit, BlueprintVisible)
	bool                                          bLoopTab;                                          // 0x0658(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bIsBackClicked;                                    // 0x0659(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bIsInitializeClicked;                              // 0x065A(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_65B[0x5];                                      // 0x065B(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	FMulticastInlineDelegateProperty_             OnTabItemClickedEvent;                             // 0x0660(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	bool                                          bUseBackIconText;                                  // 0x0670(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bUseLanguageIconText;                              // 0x0671(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bUseInitializeIconText;                            // 0x0672(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_673[0x5];                                      // 0x0673(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	FMulticastInlineDelegateProperty_             OnInitializeClickedEvent;                          // 0x0678(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	FMulticastInlineDelegateProperty_             OnBackClickedEvent;                                // 0x0688(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	FMulticastInlineDelegateProperty_             OnLanguageClickedEvent;                            // 0x0698(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)

public:
	void TabNext(bool bInCanWarp, bool* OutIsChangeIndex);
	void TabBack(bool bInCanWarp, bool* OutIsChangeIndex);
	void SetTitleVisibility();
	void SetTitleText(const class FText& InText);
	void SetTabVisibility(bool InVisible);
	void SetLanguageIconTextVisibility(bool InVisible);
	void SetIsInitializeClicked(bool InFlag);
	void SetIsBackClicked(bool InFlag);
	void SetInitializeIconTextVisibility(bool InVisible);
	void SetDefaultBackText();
	void SetBackText(const class FText& InText);
	void SetBackIconTextVisibility(bool InVisible);
	void RefreshKeyImage();
	void PreConstruct(bool IsDesignTime);
	void OnTabItemClickedEvent__DelegateSignature(int32 TabIndex);
	void OnMouseLeftClickSubPiece(class UMenuPieceBase* MenuPiece);
	void OnMouseLeaveSubPiece(class UMenuPieceBase* MenuPiece);
	void OnMouseEnterSubPiece(class UMenuPieceBase* MenuPiece);
	void OnLanguageClickedEvent__DelegateSignature();
	void OnInitializeClickedEvent__DelegateSignature();
	void OnBackClickedEvent__DelegateSignature();
	void Initialize();
	void GetTabIndex(int32* Index_0);
	void GetIsInitializeClicked(bool* OutFlag);
	void GetIsBackClicked(bool* OutFlag);
	void ExecuteUbergraph_WDT_ConfigHeader(int32 EntryPoint);
	void BndEvt__WDT_ConfigHeader_WDT_ConfigTab_K2Node_ComponentBoundEvent_0_OnTabItemClickedEvent__DelegateSignature(int32 TabIndex);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WDT_ConfigHeader_C">();
	}
	static class UWDT_ConfigHeader_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWDT_ConfigHeader_C>();
	}
};
static_assert(alignof(UWDT_ConfigHeader_C) == 0x000008, "Wrong alignment on UWDT_ConfigHeader_C");
static_assert(sizeof(UWDT_ConfigHeader_C) == 0x0006A8, "Wrong size on UWDT_ConfigHeader_C");
static_assert(offsetof(UWDT_ConfigHeader_C, UberGraphFrame) == 0x0005C8, "Member 'UWDT_ConfigHeader_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWDT_ConfigHeader_C, BackIconText) == 0x0005D0, "Member 'UWDT_ConfigHeader_C::BackIconText' has a wrong offset!");
static_assert(offsetof(UWDT_ConfigHeader_C, ConfigTitle) == 0x0005D8, "Member 'UWDT_ConfigHeader_C::ConfigTitle' has a wrong offset!");
static_assert(offsetof(UWDT_ConfigHeader_C, ConfigTitle_Shadow) == 0x0005E0, "Member 'UWDT_ConfigHeader_C::ConfigTitle_Shadow' has a wrong offset!");
static_assert(offsetof(UWDT_ConfigHeader_C, InitializeIconText) == 0x0005E8, "Member 'UWDT_ConfigHeader_C::InitializeIconText' has a wrong offset!");
static_assert(offsetof(UWDT_ConfigHeader_C, LanguageIconText) == 0x0005F0, "Member 'UWDT_ConfigHeader_C::LanguageIconText' has a wrong offset!");
static_assert(offsetof(UWDT_ConfigHeader_C, Spacer) == 0x0005F8, "Member 'UWDT_ConfigHeader_C::Spacer' has a wrong offset!");
static_assert(offsetof(UWDT_ConfigHeader_C, Spacer_45) == 0x000600, "Member 'UWDT_ConfigHeader_C::Spacer_45' has a wrong offset!");
static_assert(offsetof(UWDT_ConfigHeader_C, TitleOverlay) == 0x000608, "Member 'UWDT_ConfigHeader_C::TitleOverlay' has a wrong offset!");
static_assert(offsetof(UWDT_ConfigHeader_C, VerticalBox_Tab) == 0x000610, "Member 'UWDT_ConfigHeader_C::VerticalBox_Tab' has a wrong offset!");
static_assert(offsetof(UWDT_ConfigHeader_C, WDT_ConfigTab) == 0x000618, "Member 'UWDT_ConfigHeader_C::WDT_ConfigTab' has a wrong offset!");
static_assert(offsetof(UWDT_ConfigHeader_C, BackText) == 0x000620, "Member 'UWDT_ConfigHeader_C::BackText' has a wrong offset!");
static_assert(offsetof(UWDT_ConfigHeader_C, TitleText) == 0x000630, "Member 'UWDT_ConfigHeader_C::TitleText' has a wrong offset!");
static_assert(offsetof(UWDT_ConfigHeader_C, bIsTopMenu) == 0x000640, "Member 'UWDT_ConfigHeader_C::bIsTopMenu' has a wrong offset!");
static_assert(offsetof(UWDT_ConfigHeader_C, bUseTab) == 0x000641, "Member 'UWDT_ConfigHeader_C::bUseTab' has a wrong offset!");
static_assert(offsetof(UWDT_ConfigHeader_C, TabTextList) == 0x000648, "Member 'UWDT_ConfigHeader_C::TabTextList' has a wrong offset!");
static_assert(offsetof(UWDT_ConfigHeader_C, bLoopTab) == 0x000658, "Member 'UWDT_ConfigHeader_C::bLoopTab' has a wrong offset!");
static_assert(offsetof(UWDT_ConfigHeader_C, bIsBackClicked) == 0x000659, "Member 'UWDT_ConfigHeader_C::bIsBackClicked' has a wrong offset!");
static_assert(offsetof(UWDT_ConfigHeader_C, bIsInitializeClicked) == 0x00065A, "Member 'UWDT_ConfigHeader_C::bIsInitializeClicked' has a wrong offset!");
static_assert(offsetof(UWDT_ConfigHeader_C, OnTabItemClickedEvent) == 0x000660, "Member 'UWDT_ConfigHeader_C::OnTabItemClickedEvent' has a wrong offset!");
static_assert(offsetof(UWDT_ConfigHeader_C, bUseBackIconText) == 0x000670, "Member 'UWDT_ConfigHeader_C::bUseBackIconText' has a wrong offset!");
static_assert(offsetof(UWDT_ConfigHeader_C, bUseLanguageIconText) == 0x000671, "Member 'UWDT_ConfigHeader_C::bUseLanguageIconText' has a wrong offset!");
static_assert(offsetof(UWDT_ConfigHeader_C, bUseInitializeIconText) == 0x000672, "Member 'UWDT_ConfigHeader_C::bUseInitializeIconText' has a wrong offset!");
static_assert(offsetof(UWDT_ConfigHeader_C, OnInitializeClickedEvent) == 0x000678, "Member 'UWDT_ConfigHeader_C::OnInitializeClickedEvent' has a wrong offset!");
static_assert(offsetof(UWDT_ConfigHeader_C, OnBackClickedEvent) == 0x000688, "Member 'UWDT_ConfigHeader_C::OnBackClickedEvent' has a wrong offset!");
static_assert(offsetof(UWDT_ConfigHeader_C, OnLanguageClickedEvent) == 0x000698, "Member 'UWDT_ConfigHeader_C::OnLanguageClickedEvent' has a wrong offset!");

}

