#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WDT_PlayerIcon

#include "Basic.hpp"

#include "BasicUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WDT_PlayerIcon.WDT_PlayerIcon_C
// 0x0008 (0x04C8 - 0x04C0)
class UWDT_PlayerIcon_C final : public UUIElementBase
{
public:
	class USizeBox*                               PlayerIconSizeBox;                                 // 0x04C0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void GetWidth(double* OutValue);
	void GetHeight(double* OutValue);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WDT_PlayerIcon_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WDT_PlayerIcon_C")
	}
	static class UWDT_PlayerIcon_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWDT_PlayerIcon_C>();
	}
};
DUMPER7_ASSERTS_UWDT_PlayerIcon_C;

}

