#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WDT_Damage_Screen

#include "Basic.hpp"


namespace SDK::Params
{

// Function WDT_Damage_Screen.WDT_Damage_Screen_C.ExecuteUbergraph_WDT_Damage_Screen
// 0x0004 (0x0004 - 0x0000)
struct WDT_Damage_Screen_C_ExecuteUbergraph_WDT_Damage_Screen final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WDT_Damage_Screen_C_ExecuteUbergraph_WDT_Damage_Screen;

// Function WDT_Damage_Screen.WDT_Damage_Screen_C.GetMaterial
// 0x0010 (0x0010 - 0x0000)
struct WDT_Damage_Screen_C_GetMaterial final
{
public:
	class UMaterialInstanceDynamic*               Result;                                            // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UMaterialInstanceDynamic*               CallFunc_GetDynamicMaterial_ReturnValue;           // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WDT_Damage_Screen_C_GetMaterial;

// Function WDT_Damage_Screen.WDT_Damage_Screen_C.SetMaterial
// 0x0008 (0x0008 - 0x0000)
struct WDT_Damage_Screen_C_SetMaterial final
{
public:
	class UMaterialInterface*                     Material;                                          // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WDT_Damage_Screen_C_SetMaterial;

}

