#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WDT_KeyAssignDuplicationDialog

#include "Basic.hpp"

#include "WDT_KeyAssignDuplicationDialog_classes.hpp"
#include "WDT_KeyAssignDuplicationDialog_parameters.hpp"


namespace SDK
{

// Function WDT_KeyAssignDuplicationDialog.WDT_KeyAssignDuplicationDialog_C.WidgetAnimationEvt_GeneralYesNoDialog_Select3_K2Node_WidgetAnimationEvent_2
// (BlueprintEvent)

void UWDT_KeyAssignDuplicationDialog_C::WidgetAnimationEvt_GeneralYesNoDialog_Select3_K2Node_WidgetAnimationEvent_2()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDT_KeyAssignDuplicationDialog_C", "WidgetAnimationEvt_GeneralYesNoDialog_Select3_K2Node_WidgetAnimationEvent_2");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WDT_KeyAssignDuplicationDialog.WDT_KeyAssignDuplicationDialog_C.WidgetAnimationEvt_GeneralYesNoDialog_Select2_K2Node_WidgetAnimationEvent_0
// (BlueprintEvent)

void UWDT_KeyAssignDuplicationDialog_C::WidgetAnimationEvt_GeneralYesNoDialog_Select2_K2Node_WidgetAnimationEvent_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDT_KeyAssignDuplicationDialog_C", "WidgetAnimationEvt_GeneralYesNoDialog_Select2_K2Node_WidgetAnimationEvent_0");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WDT_KeyAssignDuplicationDialog.WDT_KeyAssignDuplicationDialog_C.WidgetAnimationEvt_GeneralYesNoDialog_Select1_K2Node_WidgetAnimationEvent_1
// (BlueprintEvent)

void UWDT_KeyAssignDuplicationDialog_C::WidgetAnimationEvt_GeneralYesNoDialog_Select1_K2Node_WidgetAnimationEvent_1()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDT_KeyAssignDuplicationDialog_C", "WidgetAnimationEvt_GeneralYesNoDialog_Select1_K2Node_WidgetAnimationEvent_1");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WDT_KeyAssignDuplicationDialog.WDT_KeyAssignDuplicationDialog_C.SetSelectDialogIndex
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWDT_KeyAssignDuplicationDialog_C::SetSelectDialogIndex(int32 Index_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDT_KeyAssignDuplicationDialog_C", "SetSelectDialogIndex");

	Params::WDT_KeyAssignDuplicationDialog_C_SetSelectDialogIndex Parms{};

	Parms.Index_0 = Index_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WDT_KeyAssignDuplicationDialog.WDT_KeyAssignDuplicationDialog_C.SequenceEvent__ENTRYPOINTWDT_KeyAssignDuplicationDialog
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UCanvasPanel*                     CanvasPanel_23                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWDT_KeyAssignDuplicationDialog_C::SequenceEvent__ENTRYPOINTWDT_KeyAssignDuplicationDialog(class UCanvasPanel* CanvasPanel_23)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDT_KeyAssignDuplicationDialog_C", "SequenceEvent__ENTRYPOINTWDT_KeyAssignDuplicationDialog");

	Params::WDT_KeyAssignDuplicationDialog_C_SequenceEvent__ENTRYPOINTWDT_KeyAssignDuplicationDialog Parms{};

	Parms.CanvasPanel_23 = CanvasPanel_23;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WDT_KeyAssignDuplicationDialog.WDT_KeyAssignDuplicationDialog_C.OnUpPressed
// (Public, BlueprintCallable, BlueprintEvent)

void UWDT_KeyAssignDuplicationDialog_C::OnUpPressed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDT_KeyAssignDuplicationDialog_C", "OnUpPressed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WDT_KeyAssignDuplicationDialog.WDT_KeyAssignDuplicationDialog_C.OnSetDialogInfo
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FDialogInfo&               InDialogInfo                                           (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UWDT_KeyAssignDuplicationDialog_C::OnSetDialogInfo(const struct FDialogInfo& InDialogInfo)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDT_KeyAssignDuplicationDialog_C", "OnSetDialogInfo");

	Params::WDT_KeyAssignDuplicationDialog_C_OnSetDialogInfo Parms{};

	Parms.InDialogInfo = std::move(InDialogInfo);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WDT_KeyAssignDuplicationDialog.WDT_KeyAssignDuplicationDialog_C.OnOpening
// (Event, Protected, BlueprintEvent)

void UWDT_KeyAssignDuplicationDialog_C::OnOpening()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDT_KeyAssignDuplicationDialog_C", "OnOpening");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WDT_KeyAssignDuplicationDialog.WDT_KeyAssignDuplicationDialog_C.OnOpened
// (Event, Protected, BlueprintEvent)

void UWDT_KeyAssignDuplicationDialog_C::OnOpened()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDT_KeyAssignDuplicationDialog_C", "OnOpened");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WDT_KeyAssignDuplicationDialog.WDT_KeyAssignDuplicationDialog_C.OnMouseLeftClickMenuPiece
// (Event, Protected, BlueprintEvent)
// Parameters:
// class UMenuPieceBase*                   MenuPiece                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWDT_KeyAssignDuplicationDialog_C::OnMouseLeftClickMenuPiece(class UMenuPieceBase* MenuPiece)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDT_KeyAssignDuplicationDialog_C", "OnMouseLeftClickMenuPiece");

	Params::WDT_KeyAssignDuplicationDialog_C_OnMouseLeftClickMenuPiece Parms{};

	Parms.MenuPiece = MenuPiece;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WDT_KeyAssignDuplicationDialog.WDT_KeyAssignDuplicationDialog_C.OnMouseEnterMenuPiece
// (Event, Protected, BlueprintEvent)
// Parameters:
// class UMenuPieceBase*                   MenuPiece                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWDT_KeyAssignDuplicationDialog_C::OnMouseEnterMenuPiece(class UMenuPieceBase* MenuPiece)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDT_KeyAssignDuplicationDialog_C", "OnMouseEnterMenuPiece");

	Params::WDT_KeyAssignDuplicationDialog_C_OnMouseEnterMenuPiece Parms{};

	Parms.MenuPiece = MenuPiece;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WDT_KeyAssignDuplicationDialog.WDT_KeyAssignDuplicationDialog_C.OnMenuInitialized
// (Event, Protected, BlueprintEvent)

void UWDT_KeyAssignDuplicationDialog_C::OnMenuInitialized()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDT_KeyAssignDuplicationDialog_C", "OnMenuInitialized");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WDT_KeyAssignDuplicationDialog.WDT_KeyAssignDuplicationDialog_C.OnGetOpenAnimation
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWidgetAnimation*                 ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash)

class UWidgetAnimation* UWDT_KeyAssignDuplicationDialog_C::OnGetOpenAnimation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDT_KeyAssignDuplicationDialog_C", "OnGetOpenAnimation");

	Params::WDT_KeyAssignDuplicationDialog_C_OnGetOpenAnimation Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WDT_KeyAssignDuplicationDialog.WDT_KeyAssignDuplicationDialog_C.OnDownPressed
// (Public, BlueprintCallable, BlueprintEvent)

void UWDT_KeyAssignDuplicationDialog_C::OnDownPressed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDT_KeyAssignDuplicationDialog_C", "OnDownPressed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WDT_KeyAssignDuplicationDialog.WDT_KeyAssignDuplicationDialog_C.OnDecidePressed
// (Public, BlueprintCallable, BlueprintEvent)

void UWDT_KeyAssignDuplicationDialog_C::OnDecidePressed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDT_KeyAssignDuplicationDialog_C", "OnDecidePressed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WDT_KeyAssignDuplicationDialog.WDT_KeyAssignDuplicationDialog_C.OnClosing
// (Event, Protected, BlueprintEvent)

void UWDT_KeyAssignDuplicationDialog_C::OnClosing()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDT_KeyAssignDuplicationDialog_C", "OnClosing");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WDT_KeyAssignDuplicationDialog.WDT_KeyAssignDuplicationDialog_C.OnClosed
// (Event, Protected, BlueprintEvent)

void UWDT_KeyAssignDuplicationDialog_C::OnClosed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDT_KeyAssignDuplicationDialog_C", "OnClosed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WDT_KeyAssignDuplicationDialog.WDT_KeyAssignDuplicationDialog_C.OnCancelPressed
// (Public, BlueprintCallable, BlueprintEvent)

void UWDT_KeyAssignDuplicationDialog_C::OnCancelPressed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDT_KeyAssignDuplicationDialog_C", "OnCancelPressed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WDT_KeyAssignDuplicationDialog.WDT_KeyAssignDuplicationDialog_C.InpActEvt_IA_UI_Up_K2Node_EnhancedInputActionEvent_3
// (BlueprintEvent)
// Parameters:
// const struct FInputActionValue&         ActionValue                                            (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// float                                   ElapsedTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   TriggeredTime                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const class UInputAction*               SourceAction                                           (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWDT_KeyAssignDuplicationDialog_C::InpActEvt_IA_UI_Up_K2Node_EnhancedInputActionEvent_3(const struct FInputActionValue& ActionValue, float ElapsedTime, float TriggeredTime, const class UInputAction* SourceAction)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDT_KeyAssignDuplicationDialog_C", "InpActEvt_IA_UI_Up_K2Node_EnhancedInputActionEvent_3");

	Params::WDT_KeyAssignDuplicationDialog_C_InpActEvt_IA_UI_Up_K2Node_EnhancedInputActionEvent_3 Parms{};

	Parms.ActionValue = std::move(ActionValue);
	Parms.ElapsedTime = ElapsedTime;
	Parms.TriggeredTime = TriggeredTime;
	Parms.SourceAction = SourceAction;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WDT_KeyAssignDuplicationDialog.WDT_KeyAssignDuplicationDialog_C.InpActEvt_IA_UI_Down_K2Node_EnhancedInputActionEvent_2
// (BlueprintEvent)
// Parameters:
// const struct FInputActionValue&         ActionValue                                            (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// float                                   ElapsedTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   TriggeredTime                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const class UInputAction*               SourceAction                                           (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWDT_KeyAssignDuplicationDialog_C::InpActEvt_IA_UI_Down_K2Node_EnhancedInputActionEvent_2(const struct FInputActionValue& ActionValue, float ElapsedTime, float TriggeredTime, const class UInputAction* SourceAction)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDT_KeyAssignDuplicationDialog_C", "InpActEvt_IA_UI_Down_K2Node_EnhancedInputActionEvent_2");

	Params::WDT_KeyAssignDuplicationDialog_C_InpActEvt_IA_UI_Down_K2Node_EnhancedInputActionEvent_2 Parms{};

	Parms.ActionValue = std::move(ActionValue);
	Parms.ElapsedTime = ElapsedTime;
	Parms.TriggeredTime = TriggeredTime;
	Parms.SourceAction = SourceAction;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WDT_KeyAssignDuplicationDialog.WDT_KeyAssignDuplicationDialog_C.InpActEvt_IA_UI_Decide_K2Node_EnhancedInputActionEvent_1
// (BlueprintEvent)
// Parameters:
// const struct FInputActionValue&         ActionValue                                            (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// float                                   ElapsedTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   TriggeredTime                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const class UInputAction*               SourceAction                                           (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWDT_KeyAssignDuplicationDialog_C::InpActEvt_IA_UI_Decide_K2Node_EnhancedInputActionEvent_1(const struct FInputActionValue& ActionValue, float ElapsedTime, float TriggeredTime, const class UInputAction* SourceAction)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDT_KeyAssignDuplicationDialog_C", "InpActEvt_IA_UI_Decide_K2Node_EnhancedInputActionEvent_1");

	Params::WDT_KeyAssignDuplicationDialog_C_InpActEvt_IA_UI_Decide_K2Node_EnhancedInputActionEvent_1 Parms{};

	Parms.ActionValue = std::move(ActionValue);
	Parms.ElapsedTime = ElapsedTime;
	Parms.TriggeredTime = TriggeredTime;
	Parms.SourceAction = SourceAction;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WDT_KeyAssignDuplicationDialog.WDT_KeyAssignDuplicationDialog_C.InpActEvt_IA_UI_Cancel_K2Node_EnhancedInputActionEvent_0
// (BlueprintEvent)
// Parameters:
// const struct FInputActionValue&         ActionValue                                            (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// float                                   ElapsedTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   TriggeredTime                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const class UInputAction*               SourceAction                                           (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWDT_KeyAssignDuplicationDialog_C::InpActEvt_IA_UI_Cancel_K2Node_EnhancedInputActionEvent_0(const struct FInputActionValue& ActionValue, float ElapsedTime, float TriggeredTime, const class UInputAction* SourceAction)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDT_KeyAssignDuplicationDialog_C", "InpActEvt_IA_UI_Cancel_K2Node_EnhancedInputActionEvent_0");

	Params::WDT_KeyAssignDuplicationDialog_C_InpActEvt_IA_UI_Cancel_K2Node_EnhancedInputActionEvent_0 Parms{};

	Parms.ActionValue = std::move(ActionValue);
	Parms.ElapsedTime = ElapsedTime;
	Parms.TriggeredTime = TriggeredTime;
	Parms.SourceAction = SourceAction;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WDT_KeyAssignDuplicationDialog.WDT_KeyAssignDuplicationDialog_C.Initialize
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWDT_KeyAssignDuplicationDialog_C::Initialize()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDT_KeyAssignDuplicationDialog_C", "Initialize");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WDT_KeyAssignDuplicationDialog.WDT_KeyAssignDuplicationDialog_C.GeneralYesNoDialogOpenAnim_Event
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UCanvasPanel*                     CanvasPanel_23                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWDT_KeyAssignDuplicationDialog_C::GeneralYesNoDialogOpenAnim_Event(class UCanvasPanel* CanvasPanel_23)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDT_KeyAssignDuplicationDialog_C", "GeneralYesNoDialogOpenAnim_Event");

	Params::WDT_KeyAssignDuplicationDialog_C_GeneralYesNoDialogOpenAnim_Event Parms{};

	Parms.CanvasPanel_23 = CanvasPanel_23;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WDT_KeyAssignDuplicationDialog.WDT_KeyAssignDuplicationDialog_C.ExecuteUbergraph_WDT_KeyAssignDuplicationDialog
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWDT_KeyAssignDuplicationDialog_C::ExecuteUbergraph_WDT_KeyAssignDuplicationDialog(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDT_KeyAssignDuplicationDialog_C", "ExecuteUbergraph_WDT_KeyAssignDuplicationDialog");

	Params::WDT_KeyAssignDuplicationDialog_C_ExecuteUbergraph_WDT_KeyAssignDuplicationDialog Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WDT_KeyAssignDuplicationDialog.WDT_KeyAssignDuplicationDialog_C.BP_OnDeactivated
// (Event, Protected, BlueprintEvent)

void UWDT_KeyAssignDuplicationDialog_C::BP_OnDeactivated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDT_KeyAssignDuplicationDialog_C", "BP_OnDeactivated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WDT_KeyAssignDuplicationDialog.WDT_KeyAssignDuplicationDialog_C.BP_OnActivated
// (Event, Protected, BlueprintEvent)

void UWDT_KeyAssignDuplicationDialog_C::BP_OnActivated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDT_KeyAssignDuplicationDialog_C", "BP_OnActivated");

	UObject::ProcessEvent(Func, nullptr);
}

}

