#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WDT_StatusSummary_Resistant

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "WDT_Status_PieceBase_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WDT_StatusSummary_Resistant.WDT_StatusSummary_Resistant_C
// 0x0028 (0x06F0 - 0x06C8)
class UWDT_StatusSummary_Resistant_C final : public UWDT_Status_PieceBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_WDT_StatusSummary_Resistant_C;      // 0x06C8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWDT_ArticleDiffArrowElement_C*         Arrow_ResistantValue;                              // 0x06D0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 ResistantIcon;                                     // 0x06D8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             ResistantValue;                                    // 0x06E0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTexture2D*                             IconTexture;                                       // 0x06E8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WDT_StatusSummary_Resistant(int32 EntryPoint);
	void PreConstruct(bool IsDesignTime);
	void SetValue(int32 InValue);
	void SetValueComparison(int32 InCurrentValue, int32 InTargetValue);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WDT_StatusSummary_Resistant_C">();
	}
	static class UWDT_StatusSummary_Resistant_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWDT_StatusSummary_Resistant_C>();
	}
};
static_assert(alignof(UWDT_StatusSummary_Resistant_C) == 0x000008, "Wrong alignment on UWDT_StatusSummary_Resistant_C");
static_assert(sizeof(UWDT_StatusSummary_Resistant_C) == 0x0006F0, "Wrong size on UWDT_StatusSummary_Resistant_C");
static_assert(offsetof(UWDT_StatusSummary_Resistant_C, UberGraphFrame_WDT_StatusSummary_Resistant_C) == 0x0006C8, "Member 'UWDT_StatusSummary_Resistant_C::UberGraphFrame_WDT_StatusSummary_Resistant_C' has a wrong offset!");
static_assert(offsetof(UWDT_StatusSummary_Resistant_C, Arrow_ResistantValue) == 0x0006D0, "Member 'UWDT_StatusSummary_Resistant_C::Arrow_ResistantValue' has a wrong offset!");
static_assert(offsetof(UWDT_StatusSummary_Resistant_C, ResistantIcon) == 0x0006D8, "Member 'UWDT_StatusSummary_Resistant_C::ResistantIcon' has a wrong offset!");
static_assert(offsetof(UWDT_StatusSummary_Resistant_C, ResistantValue) == 0x0006E0, "Member 'UWDT_StatusSummary_Resistant_C::ResistantValue' has a wrong offset!");
static_assert(offsetof(UWDT_StatusSummary_Resistant_C, IconTexture) == 0x0006E8, "Member 'UWDT_StatusSummary_Resistant_C::IconTexture' has a wrong offset!");

}

