#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WDT_Status_GuardPerformance

#include "Basic.hpp"

#include "WDT_Status_PieceBase_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WDT_Status_GuardPerformance.WDT_Status_GuardPerformance_C
// 0x0010 (0x06D8 - 0x06C8)
class UWDT_Status_GuardPerformance_C final : public UWDT_Status_PieceBase_C
{
public:
	class UCommonTextBlock*                       CommonTex_Guard;                                   // 0x06C8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_27;                                          // 0x06D0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void SetGuardPerformance(int32 InGuardPerformance);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WDT_Status_GuardPerformance_C">();
	}
	static class UWDT_Status_GuardPerformance_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWDT_Status_GuardPerformance_C>();
	}
};
static_assert(alignof(UWDT_Status_GuardPerformance_C) == 0x000008, "Wrong alignment on UWDT_Status_GuardPerformance_C");
static_assert(sizeof(UWDT_Status_GuardPerformance_C) == 0x0006D8, "Wrong size on UWDT_Status_GuardPerformance_C");
static_assert(offsetof(UWDT_Status_GuardPerformance_C, CommonTex_Guard) == 0x0006C8, "Member 'UWDT_Status_GuardPerformance_C::CommonTex_Guard' has a wrong offset!");
static_assert(offsetof(UWDT_Status_GuardPerformance_C, Image_27) == 0x0006D0, "Member 'UWDT_Status_GuardPerformance_C::Image_27' has a wrong offset!");

}

