#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WDT_SimplifiedArticleInfo

#include "Basic.hpp"

#include "WDT_SimplifiedArticleInfo_classes.hpp"
#include "WDT_SimplifiedArticleInfo_parameters.hpp"


namespace SDK
{

// Function WDT_SimplifiedArticleInfo.WDT_SimplifiedArticleInfo_C.EnhanceInfo
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   EnhanceLevel                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// TSoftObjectPtr<class UTexture2D>        EnchantIcon_0                                          (BlueprintVisible, BlueprintReadOnly, Parm, UObjectWrapper, HasGetValueTypeHash)
// const struct FGameplayTag&              EnchantTag                                             (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)

void UWDT_SimplifiedArticleInfo_C::EnhanceInfo(int32 EnhanceLevel, TSoftObjectPtr<class UTexture2D> EnchantIcon_0, const struct FGameplayTag& EnchantTag)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDT_SimplifiedArticleInfo_C", "EnhanceInfo");

	Params::WDT_SimplifiedArticleInfo_C_EnhanceInfo Parms{};

	Parms.EnhanceLevel = EnhanceLevel;
	Parms.EnchantIcon_0 = EnchantIcon_0;
	Parms.EnchantTag = std::move(EnchantTag);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WDT_SimplifiedArticleInfo.WDT_SimplifiedArticleInfo_C.IsEmpty
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool*                                   NewParam                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWDT_SimplifiedArticleInfo_C::IsEmpty(bool* NewParam)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDT_SimplifiedArticleInfo_C", "IsEmpty");

	Params::WDT_SimplifiedArticleInfo_C_IsEmpty Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (NewParam != nullptr)
		*NewParam = Parms.NewParam;
}


// Function WDT_SimplifiedArticleInfo.WDT_SimplifiedArticleInfo_C.SetArticleInfo
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FUIArticleInfo&            ArticleInfo                                            (BlueprintVisible, BlueprintReadOnly, Parm)
// int32                                   EnhancementLevel                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// TSoftObjectPtr<class UTexture2D>        EnchantLcon                                            (BlueprintVisible, BlueprintReadOnly, Parm, UObjectWrapper, HasGetValueTypeHash)
// const struct FGameplayTag&              InEnchantTag                                           (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)

void UWDT_SimplifiedArticleInfo_C::SetArticleInfo(const struct FUIArticleInfo& ArticleInfo, int32 EnhancementLevel, TSoftObjectPtr<class UTexture2D> EnchantLcon, const struct FGameplayTag& InEnchantTag)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDT_SimplifiedArticleInfo_C", "SetArticleInfo");

	Params::WDT_SimplifiedArticleInfo_C_SetArticleInfo Parms{};

	Parms.ArticleInfo = std::move(ArticleInfo);
	Parms.EnhancementLevel = EnhancementLevel;
	Parms.EnchantLcon = EnchantLcon;
	Parms.InEnchantTag = std::move(InEnchantTag);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WDT_SimplifiedArticleInfo.WDT_SimplifiedArticleInfo_C.SetEmpty
// (Public, BlueprintCallable, BlueprintEvent)

void UWDT_SimplifiedArticleInfo_C::SetEmpty()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDT_SimplifiedArticleInfo_C", "SetEmpty");

	UObject::ProcessEvent(Func, nullptr);
}

}

