#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WDT_TitleMenu_BG_01

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BasicUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WDT_TitleMenu_BG_01.WDT_TitleMenu_BG_01_C
// 0x0008 (0x04C8 - 0x04C0)
class UWDT_TitleMenu_BG_01_C final : public UUIElementBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x04C0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void BP_OnActivated();
	void ExecuteUbergraph_WDT_TitleMenu_BG_01(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WDT_TitleMenu_BG_01_C">();
	}
	static class UWDT_TitleMenu_BG_01_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWDT_TitleMenu_BG_01_C>();
	}
};
static_assert(alignof(UWDT_TitleMenu_BG_01_C) == 0x000008, "Wrong alignment on UWDT_TitleMenu_BG_01_C");
static_assert(sizeof(UWDT_TitleMenu_BG_01_C) == 0x0004C8, "Wrong size on UWDT_TitleMenu_BG_01_C");
static_assert(offsetof(UWDT_TitleMenu_BG_01_C, UberGraphFrame) == 0x0004C0, "Member 'UWDT_TitleMenu_BG_01_C::UberGraphFrame' has a wrong offset!");

}

