#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WDT_ConfigIconTextPiece

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BasicUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WDT_ConfigIconTextPiece.WDT_ConfigIconTextPiece_C
// 0x0048 (0x0610 - 0x05C8)
class UWDT_ConfigIconTextPiece_C final : public UMenuPieceBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x05C8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UCommonTextBlock*                       ConfigCancelText;                                  // 0x05D0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       ConfigCancelText_Shadow;                           // 0x05D8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class URichTextBlock*                         IconText_L;                                        // 0x05E0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 SelectImage;                                       // 0x05E8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class FText                                   TitleText;                                         // 0x05F0(0x0010)(Edit, BlueprintVisible)
	class FText                                   IconText;                                          // 0x0600(0x0010)(Edit, BlueprintVisible)

public:
	void SetText(const class FText& SetText_0);
	bool Select(bool PlayAnimation_0);
	void RefreshKeyImage();
	void PreConstruct(bool IsDesignTime);
	void ExecuteUbergraph_WDT_ConfigIconTextPiece(int32 EntryPoint);
	bool Deselect(bool PlayAnimation_0);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WDT_ConfigIconTextPiece_C">();
	}
	static class UWDT_ConfigIconTextPiece_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWDT_ConfigIconTextPiece_C>();
	}
};
static_assert(alignof(UWDT_ConfigIconTextPiece_C) == 0x000008, "Wrong alignment on UWDT_ConfigIconTextPiece_C");
static_assert(sizeof(UWDT_ConfigIconTextPiece_C) == 0x000610, "Wrong size on UWDT_ConfigIconTextPiece_C");
static_assert(offsetof(UWDT_ConfigIconTextPiece_C, UberGraphFrame) == 0x0005C8, "Member 'UWDT_ConfigIconTextPiece_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWDT_ConfigIconTextPiece_C, ConfigCancelText) == 0x0005D0, "Member 'UWDT_ConfigIconTextPiece_C::ConfigCancelText' has a wrong offset!");
static_assert(offsetof(UWDT_ConfigIconTextPiece_C, ConfigCancelText_Shadow) == 0x0005D8, "Member 'UWDT_ConfigIconTextPiece_C::ConfigCancelText_Shadow' has a wrong offset!");
static_assert(offsetof(UWDT_ConfigIconTextPiece_C, IconText_L) == 0x0005E0, "Member 'UWDT_ConfigIconTextPiece_C::IconText_L' has a wrong offset!");
static_assert(offsetof(UWDT_ConfigIconTextPiece_C, SelectImage) == 0x0005E8, "Member 'UWDT_ConfigIconTextPiece_C::SelectImage' has a wrong offset!");
static_assert(offsetof(UWDT_ConfigIconTextPiece_C, TitleText) == 0x0005F0, "Member 'UWDT_ConfigIconTextPiece_C::TitleText' has a wrong offset!");
static_assert(offsetof(UWDT_ConfigIconTextPiece_C, IconText) == 0x000600, "Member 'UWDT_ConfigIconTextPiece_C::IconText' has a wrong offset!");

}

